const db=window.dalimgariSupabase;
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const fmt=d=>new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(d));
const t=(key)=>({en:{feed:"Community feed",noMedia:"No media selected",publish:"Publish",published:"Post published.",comment:"Write a comment…",noComments:"No comments yet.",members:"members",noMembers:"No members found.",noEvents:"No upcoming events.",noMediaGallery:"No media has been shared yet.",album:"Album",noAlbum:"No album",reportSent:"Report submitted for review.",theme:"Theme preset",language:"Interface language"},bn:{feed:"কমিউনিটি ফিড",noMedia:"কোনো মিডিয়া নির্বাচিত নয়",publish:"প্রকাশ করুন",published:"পোস্ট প্রকাশ হয়েছে।",comment:"মন্তব্য লিখুন…",noComments:"এখনও কোনো মন্তব্য নেই।",members:"জন সদস্য",noMembers:"কোনো সদস্য পাওয়া যায়নি।",noEvents:"কোনো আসন্ন ইভেন্ট নেই।",noMediaGallery:"এখনও কোনো মিডিয়া শেয়ার করা হয়নি।",album:"অ্যালবাম",noAlbum:"কোনো অ্যালবাম নয়",reportSent:"রিপোর্ট পর্যালোচনার জন্য পাঠানো হয়েছে।",theme:"থিম প্রিসেট",language:"ইন্টারফেস ভাষা"}}[document.documentElement.lang==="bn"?"bn":"en"][key]||key);
async function session(){return (await db?.auth.getSession())?.data?.session||null}
function msg(text,type="info"){const o=document.querySelector("[data-community-message]");if(o){o.textContent=text;o.dataset.state=type}}
function mediaMarkup(m){if(!m?.media_url)return"";const url=esc(m.media_url),alt=esc(m.title||"Community media");return m.media_type==="video"?'<video class="post-media-video" controls preload="metadata" src="'+url+'"></video>':'<img class="post-media-image" loading="lazy" src="'+url+'" alt="'+alt+'">'}
function renderPostMedia(items){return items?.length?'<div class="post-media-grid">'+items.map(x=>mediaMarkup(x.Media)).join("")+"</div>":""}
async function loadCommunityProfiles(ids=[]){if(!ids.length)return new Map();const {data}=await db.from("community_profiles").select("user_id,username,avatar_url,account_type,is_verified").in("user_id",ids);return new Map((data||[]).map(u=>[u.user_id,u]))}
async function loadFeed(root){
 const {data,error}=await db.from("posts").select("id,user_id,content,created_at,comments(id,user_id,content,created_at),post_reactions(user_id,reaction),post_media(sort_order,Media:Media!post_media_media_id_fkey(id,title,media_type,media_url,thumbnail_url))").order("created_at",{ascending:false}).limit(40);
 if(error){root.innerHTML='<div class="empty">Could not load the community feed.</div>';return}
 if(!data?.length){root.innerHTML='<div class="empty">No posts yet. Be the first to share an update.</div>';return}
 const ids=[...new Set(data.flatMap(p=>[p.user_id,...(p.comments||[]).map(c=>c.user_id)]))],profiles=await loadCommunityProfiles(ids),s=await session(),current=s?.user?.id;root.innerHTML=data.map(p=>{const author=profiles.get(p.user_id),likes=p.post_reactions?.length||0,own=p.post_reactions?.some(r=>r.user_id===current),mine=p.user_id===current;
 return '<article class="card post" data-post="'+p.id+'"><div class="post-head"><div><span class="post-author">'+esc(author?.username||"Community member")+'</span><div class="post-time">'+esc(fmt(p.created_at))+'</div></div><button class="comment-toggle" data-comments="'+p.id+'">Comments ('+(p.comments?.length||0)+')</button></div><div class="post-body">'+esc(p.content)+'</div>'+renderPostMedia(p.post_media?.sort((a,b)=>(a.sort_order||0)-(b.sort_order||0)))+'<div class="post-actions"><button data-like="'+p.id+'">'+(own?"Unlike":"Like")+" · "+likes+'</button><button data-report="'+p.id+'">Report</button>'+(mine?'<button data-edit-post="'+p.id+'">Edit</button><button data-delete-post="'+p.id+'">Delete</button>':"")+'</div><div class="comments" data-comments-box="'+p.id+'" hidden>'+((p.comments||[]).map(c=>{const author=profiles.get(c.user_id);return '<div class="comment"><strong>'+esc(author?.username||"Member")+'</strong> <span class="muted">'+esc(fmt(c.created_at))+'</span><div>'+esc(c.content)+'</div></div>').join("")||'<div class="muted">'+t("noComments")+'</div>')+'<form class="comment-form" data-comment-form="'+p.id+'"><input required maxlength="2000" placeholder="'+t("comment")+'"><button class="button button--secondary">Post</button></form></div></article>'}).join("")
}
async function loadAnnouncements(root){const {data}=await db.from("announcements").select("title,content,created_at").eq("published",true).order("created_at",{ascending:false}).limit(5);root.innerHTML=data?.length?data.map(a=>'<div class="list-item"><strong>'+esc(a.title)+'</strong><p>'+esc(a.content)+'</p><small class="muted">'+esc(fmt(a.created_at))+'</small></div>').join(""):'<div class="empty">No announcements.</div>'}
async function loadMembers(root){const {data,error}=await db.from("community_profiles").select("user_id,username,avatar_url,account_type,is_verified").order("username").limit(100);if(error){root.innerHTML='<div class="empty">Members are unavailable.</div>';return}document.querySelector("[data-member-count]").textContent=(data?.length||0)+" "+t("members");root.innerHTML=data?.length?data.map(u=>'<article class="card member-card"><img class="member-avatar" src="'+esc(u.avatar_url||"")+'" onerror="this.style.visibility=\'hidden\'" alt=""><div><strong>'+esc(u.username||"Member")+'</strong><div class="muted">'+esc(u.account_type||"member")+(u.is_verified?" · verified":"")+'</div></div></article>').join(""):'<div class="empty">'+t("noMembers")+"</div>"}
async function loadEvents(root){const {data,error}=await db.from("events").select("id,title,description,location,starts_at,ends_at,event_rsvps(user_id,status)").gte("starts_at",new Date().toISOString()).order("starts_at").limit(30);if(error){root.innerHTML='<div class="empty">Events are unavailable.</div>';return}const s=await session();root.innerHTML=data?.length?data.map(e=>{const mine=e.event_rsvps?.find(r=>r.user_id===s?.user.id);return '<article class="card event-card"><h3>'+esc(e.title)+'</h3><time>'+esc(fmt(e.starts_at))+'</time><p>'+esc(e.description||"")+'</p><p class="muted">'+esc(e.location||"Location to be announced")+'</p><button class="button button--secondary" data-rsvp="'+e.id+'">'+(mine?.status==="going"?"Going":mine?.status==="interested"?"Interested":"Join event")+'</button><span class="muted"> · '+(e.event_rsvps?.filter(r=>r.status==="going").length||0)+' going</span></article>'}).join(""):'<div class="empty">'+t("noEvents")+"</div>"}
async function loadAlbums(){const {data}=await db.from("Album").select("id,name").eq("visibility","public").order("created_at",{ascending:false}).limit(50);const s=document.querySelector("[data-gallery-album]");if(s)s.innerHTML='<option value="">'+t("noAlbum")+"</option>"+(data||[]).map(a=>'<option value="'+esc(a.id)+'">'+esc(a.name)+'</option>').join("")}
async function loadGallery(root){const {data,error}=await db.from("Media").select("id,title,description,media_type,media_url,thumbnail_url,album_id,created_at").order("created_at",{ascending:false}).limit(60);if(error){root.innerHTML='<div class="empty">Gallery is unavailable.</div>';return}root.innerHTML=data?.length?data.map(m=>'<article class="card media-card">'+mediaMarkup(m)+'<div class="card-body"><strong>'+esc(m.title||"Untitled")+'</strong><p>'+esc(m.description||"")+'</p></div></article>').join(""):'<div class="empty">'+t("noMediaGallery")+"</div>"}
function previewFiles(files){const box=document.querySelector("[data-post-media-preview]"),label=document.querySelector("[data-selected-media]");if(label)label.textContent=files.length?files.length+" file(s) selected":t("noMedia");if(!box)return;box.hidden=!files.length;box.innerHTML=files.map(f=>{const url=URL.createObjectURL(f);return f.type.startsWith("video/")?'<video controls src="'+url+'"></video>':'<img src="'+url+'" alt="">'}).join("")}
async function uploadFiles(files,albumId=""){const s=await session();if(!s){location.hash="content/login.html";return[]}const media=[];for(const file of files){if(!/^(image|video)\//.test(file.type))continue;if(file.size>50*1024*1024){msg("Files must be 50 MB or smaller.","error");continue}const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_"),path=s.user.id+"/"+crypto.randomUUID()+"-"+safe;const up=await db.storage.from("community-media").upload(path,file,{upsert:false,contentType:file.type,cacheControl:"31536000"});if(up.error){msg(up.error.message,"error");continue}const u=db.storage.from("community-media").getPublicUrl(path);const type=file.type.startsWith("video/")?"video":"image";const ins=await db.from("Media").insert({user_id:s.user.id,title:file.name,media_type:type,mime_type:file.type,file_size:file.size,media_url:u.data.publicUrl,album_id:albumId||null,visibility:"public"}).select("id,title,media_type,media_url").single();if(ins.error){msg(ins.error.message,"error");continue}media.push(ins.data)}return media}
async function createPost(){const s=await session();if(!s){location.hash="content/login.html";return}const input=document.querySelector("[data-post-content]"),files=[...(document.querySelector("[data-media-files]")?.files||[])],content=input.value.trim();if(!content&&!files.length)return msg("Write something or add media before publishing.","error");const {data,error}=await db.from("posts").insert({user_id:s.user.id,content:content||"Shared media",visibility:"public"}).select("id").single();if(error)return msg(error.message,"error");if(files.length){const media=await uploadFiles(files);if(media.length){const links=media.map((m,i)=>({post_id:data.id,media_id:m.id,sort_order:i}));const lr=await db.from("post_media").insert(links);if(lr.error)msg(lr.error.message,"error")}}input.value="";const picker=document.querySelector("[data-media-files]");if(picker)picker.value="";previewFiles([]);msg(t("published"),"success");await loadFeed(document.querySelector("[data-feed]"))}
async function react(id){const s=await session();if(!s){location.hash="content/login.html";return}const {data}=await db.from("post_reactions").select("post_id").eq("post_id",id).eq("user_id",s.user.id).maybeSingle();const q=data?db.from("post_reactions").delete().eq("post_id",id).eq("user_id",s.user.id):db.from("post_reactions").insert({post_id:id,user_id:s.user.id,reaction:"like"});const {error}=await q;if(error)msg(error.message,"error");else loadFeed(document.querySelector("[data-feed]"))}
async function comment(id,form){const s=await session();if(!s){location.hash="content/login.html";return}const input=form.querySelector("input"),content=input.value.trim();if(!content)return;const {error}=await db.from("comments").insert({post_id:id,user_id:s.user.id,content});if(error)msg(error.message,"error");else{input.value="";loadFeed(document.querySelector("[data-feed]"))}}
async function rsvp(id){const s=await session();if(!s){location.hash="content/login.html";return}const {data}=await db.from("event_rsvps").select("status").eq("event_id",id).eq("user_id",s.user.id).maybeSingle();const status=data?.status==="going"?"interested":"going";const q=data?db.from("event_rsvps").update({status}).eq("event_id",id).eq("user_id",s.user.id):db.from("event_rsvps").insert({event_id:id,user_id:s.user.id,status});const {error}=await q;if(error)msg(error.message,"error");else loadEvents(document.querySelector("[data-events]"))}
async function report(id){const s=await session();if(!s){location.hash="content/login.html";return}const reason=prompt("Why are you reporting this post?");if(!reason?.trim())return;const {error}=await db.from("reports").insert({reporter_id:s.user.id,post_id:id,reason:reason.trim()});if(error)msg(error.message,"error");else msg(t("reportSent"),"success")}
async function newEvent(){const s=await session();if(!s){location.hash="content/login.html";return}const title=prompt("Event title");if(!title)return;const date=prompt("Start date/time (e.g. 2026-12-01T18:00)");if(!date)return;const description=prompt("Description (optional)")||"",locationText=prompt("Location (optional)")||"";const start=new Date(date);if(Number.isNaN(start.getTime()))return msg("Invalid event date.","error");const {error}=await db.from("events").insert({creator_id:s.user.id,title:title.trim(),description,location:locationText,starts_at:start.toISOString()});if(error)msg(error.message,"error");else{msg("Event created.","success");loadEvents(document.querySelector("[data-events]"))}}
async function createAlbum(){const s=await session();if(!s){location.hash="content/login.html";return}const name=prompt("Album name");if(!name?.trim())return;const r=await db.from("Album").insert({user_id:s.user.id,name:name.trim(),visibility:"public"});if(r.error)msg(r.error.message,"error");else{msg("Album created.","success");await loadAlbums()}}
async function savePreferences(){const s=await session();const l=document.querySelector("[data-language]"),m=document.querySelector("[data-theme-mode]"),p=document.querySelector("[data-theme-preset]");if(!s||!l||!m||!p)return;const v={user_id:s.user.id,language:l.value,theme_mode:m.value,theme_preset:p.value},r=await db.from("user_preferences").upsert(v);if(r.error)return msg(r.error.message,"error");applyTheme(v.theme_mode,v.theme_preset);applyLanguage(v.language)}
async function applyTheme(mode,preset){const r=await db.from("theme_presets").select("tokens").eq("key",preset).eq("is_active",true).maybeSingle();const tokens=r.data?.tokens||{};const root=document.documentElement;root.dataset.themeMode=mode;root.dataset.themePreset=preset;Object.entries(tokens).forEach(([k,v])=>root.style.setProperty("--"+k,v));if(mode==="dark")root.classList.add("force-dark");else root.classList.remove("force-dark")}
function applyLanguage(language){document.documentElement.lang=language;const dict={en:{feed:"Community feed",members:"Members",events:"Events",gallery:"Gallery",settings:"Preferences",publish:"Publish",refresh:"Refresh"},bn:{feed:"কমিউনিটি ফিড",members:"সদস্য",events:"ইভেন্ট",gallery:"গ্যালারি",settings:"পছন্দ",publish:"প্রকাশ করুন",refresh:"রিফ্রেশ"}}[language]||{};const map={"Community feed":dict.feed,"Members":dict.members,"Events":dict.events,"Gallery":dict.gallery,"Preferences":dict.settings,"Publish":dict.publish,"Refresh":dict.refresh};document.querySelectorAll("[data-community-tab]").forEach(b=>{const v=map[b.textContent.trim()];if(v)b.textContent=v});const pub=document.querySelector("[data-create-post]");if(pub&&dict.publish)pub.textContent=dict.publish;const ref=document.querySelector("[data-refresh-feed]");if(ref&&dict.refresh)ref.textContent=dict.refresh}
async function loadPreferences(){const s=await session(),p=document.querySelector("[data-theme-preset]"),m=document.querySelector("[data-theme-mode]"),l=document.querySelector("[data-language]");if(!p||!m||!l)return;const {data:opt}=await db.from("platform_options").select("value").eq("key","theme_presets").maybeSingle(),keys=opt?.value||["classic","modern","future"],tres=await db.from("theme_presets").select("key,name").in("key",keys).eq("is_active",true).order("name");p.innerHTML=(tres.data||[]).map(x=>'<option value="'+esc(x.key)+'">'+esc(x.name)+"</option>").join("");if(s){const r=await db.from("user_preferences").select("language,theme_mode,theme_preset").eq("user_id",s.user.id).maybeSingle(),v=r.data||{language:"en",theme_mode:"system",theme_preset:keys[0]||"classic"};l.value=v.language;m.value=v.theme_mode;p.value=v.theme_preset;await applyTheme(v.theme_mode,v.theme_preset);applyLanguage(v.language)}l.onchange=savePreferences;m.onchange=savePreferences;p.onchange=savePreferences}
async function editPost(id){const s=await session();if(!s)return;const r=await db.from("posts").select("content").eq("id",id).eq("user_id",s.user.id).single(),content=prompt("Edit post",r.data?.content||"");if(content===null)return;const u=await db.from("posts").update({content:content.trim()}).eq("id",id).eq("user_id",s.user.id);if(u.error)msg(u.error.message,"error");else loadFeed(document.querySelector("[data-feed]"))}
async function deletePost(id){const s=await session();if(!s||!confirm("Delete this post?"))return;const r=await db.from("posts").delete().eq("id",id).eq("user_id",s.user.id);if(r.error)msg(r.error.message,"error");else loadFeed(document.querySelector("[data-feed]"))}
export async function initCommunity(){
 if(!db)return;const feed=document.querySelector("[data-feed]");if(!feed)return;
 document.querySelector("[data-create-post]")?.addEventListener("click",createPost);
 document.querySelector("[data-refresh-feed]")?.addEventListener("click",()=>loadFeed(feed));
 document.querySelector("[data-new-event]")?.addEventListener("click",newEvent);
 document.querySelector("[data-create-album]")?.addEventListener("click",createAlbum);
 document.querySelector("[data-media-files]")?.addEventListener("change",e=>previewFiles([...e.target.files]));
 document.querySelector("[data-gallery-upload]")?.addEventListener("change",async e=>{await uploadFiles([...e.target.files],document.querySelector("[data-gallery-album]")?.value||"");e.target.value="";await loadGallery(document.querySelector("[data-gallery]"));await loadAlbums()});
 document.querySelectorAll("[data-community-tab]").forEach((b,i)=>b.addEventListener("click",async()=>{document.querySelectorAll("[data-community-tab]").forEach(x=>{const active=x===b;x.classList.toggle("is-active",active);x.setAttribute("aria-selected",String(active));x.tabIndex=active?0:-1});document.querySelectorAll("[data-community-view]").forEach(x=>x.hidden=x.dataset.communityView!==b.dataset.communityTab);if(b.dataset.communityTab==="members")loadMembers(document.querySelector("[data-members]"));if(b.dataset.communityTab==="events")loadEvents(document.querySelector("[data-events]"));if(b.dataset.communityTab==="gallery"){loadAlbums();loadGallery(document.querySelector("[data-gallery]"))}if(b.dataset.communityTab==="settings")loadPreferences()}));
 document.querySelector("[data-media-files]")?.addEventListener("keydown",()=>{});
 document.addEventListener("click",e=>{const like=e.target.closest("[data-like]"),toggle=e.target.closest("[data-comments]"),rep=e.target.closest("[data-report]"),rv=e.target.closest("[data-rsvp]"),edit=e.target.closest("[data-edit-post]"),del=e.target.closest("[data-delete-post]");if(like)react(like.dataset.like);if(rep)report(rep.dataset.report);if(rv)rsvp(rv.dataset.rsvp);if(edit)editPost(edit.dataset.editPost);if(del)deletePost(del.dataset.deletePost);if(toggle){const box=document.querySelector('[data-comments-box="'+toggle.dataset.comments+'"]');if(box)box.hidden=!box.hidden}});
 document.addEventListener("submit",e=>{const f=e.target.closest("[data-comment-form]");if(f){e.preventDefault();comment(f.dataset.commentForm,f)}});
 await Promise.all([loadFeed(feed),loadAnnouncements(document.querySelector("[data-announcements]")),loadEvents(document.querySelector("[data-event-preview]"))]);
}