const db=window.dalimgariSupabase;
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}))[c]);
const fmt=d=>new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(d));
async function session(){return (await db?.auth.getSession())?.data?.session||null}
function msg(text,type="info"){const o=document.querySelector("[data-community-message]");if(o){o.textContent=text;o.dataset.state=type}}
async function loadFeed(root){
 const {data,error}=await db.from("posts").select("id,user_id,content,created_at,User:User!posts_user_id_fkey(username,avatar_url),comments(id,user_id,content,created_at,User:User!comments_user_id_fkey(username)),post_reactions(user_id,reaction)").order("created_at",{ascending:false}).limit(40);
 if(error){root.innerHTML='<div class="empty">Could not load the community feed.</div>';return}
 if(!data?.length){root.innerHTML='<div class="empty">No posts yet. Be the first to share an update.</div>';return}
 const s=await session(); root.innerHTML=data.map(p=>{const likes=p.post_reactions?.length||0;const own=p.post_reactions?.some(r=>r.user_id===s?.user.id);return '<article class="card post" data-post="'+p.id+'"><div class="post-head"><div><span class="post-author">'+esc(p.User?.username||"Community member")+'</span><div class="post-time">'+esc(fmt(p.created_at))+'</div></div><button class="comment-toggle" data-comments="'+p.id+'">Comments ('+(p.comments?.length||0)+')</button></div><div class="post-body">'+esc(p.content)+'</div><div class="post-actions"><button data-like="'+p.id+'">'+(own?"Unlike":"Like")+' · '+likes+'</button><button data-report="'+p.id+'">Report</button></div><div class="comments" data-comments-box="'+p.id+'" hidden>'+((p.comments||[]).map(c=>'<div class="comment"><strong>'+esc(c.User?.username||"Member")+'</strong> <span class="muted">'+esc(fmt(c.created_at))+'</span><div>'+esc(c.content)+'</div></div>').join("")||'<div class="muted">No comments yet.</div>')+'<form class="comment-form" data-comment-form="'+p.id+'"><input required maxlength="2000" placeholder="Write a comment…"><button class="button button--secondary">Post</button></form></div></article>'}).join("");
}
async function loadAnnouncements(root){const {data}=await db.from("announcements").select("title,content,created_at").eq("published",true).order("created_at",{ascending:false}).limit(5);root.innerHTML=data?.length?data.map(a=>'<div class="list-item"><strong>'+esc(a.title)+'</strong><p>'+esc(a.content)+'</p><small class="muted">'+esc(fmt(a.created_at))+'</small></div>').join(""):'<div class="empty">No announcements.</div>'}
async function loadMembers(root){const {data,error}=await db.from("User").select("user_id,username,email,avatar_url,account_type,is_verified").order("username").limit(100);if(error){root.innerHTML='<div class="empty">Members are unavailable.</div>';return}document.querySelector("[data-member-count]").textContent=(data?.length||0)+" members";root.innerHTML=data?.length?data.map(u=>'<article class="card member-card"><img class="member-avatar" src="'+esc(u.avatar_url||"")+'" onerror="this.style.visibility=\'hidden\'" alt=""><div><strong>'+esc(u.username||"Member")+'</strong><div class="muted">'+esc(u.account_type||"member")+(u.is_verified?" · verified":"")+'</div></div></article>').join(""):'<div class="empty">No members found.</div>'}
async function loadEvents(root){const {data}=await db.from("events").select("id,title,description,location,starts_at,ends_at,event_rsvps(user_id,status)").gte("starts_at",new Date().toISOString()).order("starts_at").limit(30);const s=await session();root.innerHTML=data?.length?data.map(e=>{const mine=e.event_rsvps?.find(r=>r.user_id===s?.user.id);return '<article class="card event-card"><h3>'+esc(e.title)+'</h3><time>'+esc(fmt(e.starts_at))+'</time><p>'+esc(e.description||"")+'</p><p class="muted">'+esc(e.location||"Location to be announced")+'</p><button class="button button--secondary" data-rsvp="'+e.id+'">'+(mine?mine.status==="going"?"Going":"Interested":"Join event")+'</button><span class="muted"> · '+(e.event_rsvps?.filter(r=>r.status==="going").length||0)+' going</span></article>'}).join(""):'<div class="empty">No upcoming events.</div>'}
async function loadGallery(root){const {data,error}=await db.from("Media").select("id,title,description,media_type,media_url,thumbnail_url,visibility,created_at").order("created_at",{ascending:false}).limit(60);if(error){root.innerHTML='<div class="empty">Gallery is unavailable.</div>';return}root.innerHTML=data?.length?data.map(m=>'<article class="card media-card">'+(m.thumbnail_url||m.media_url?'<img src="'+esc(m.thumbnail_url||m.media_url)+'" alt="'+esc(m.title||"Community media")+'">':'')+'<div class="card-body"><strong>'+esc(m.title||"Untitled")+'</strong><p>'+esc(m.description||"")+'</p></div></article>').join(""):'<div class="empty">No media has been shared yet.</div>'}
async function createPost(){const s=await session();if(!s){location.hash="content/login.html";return}const input=document.querySelector("[data-post-content]");const content=input.value.trim();if(!content)return msg("Write something before publishing.","error");const {error}=await db.from("posts").insert({user_id:s.user.id,content,visibility:"public"});if(error)return msg(error.message,"error");input.value="";msg("Post published.","success");await loadFeed(document.querySelector("[data-feed]"))}
async function react(id){const s=await session();if(!s){location.hash="content/login.html";return}const {data}=await db.from("post_reactions").select("post_id").eq("post_id",id).eq("user_id",s.user.id).maybeSingle();const q=data?db.from("post_reactions").delete().eq("post_id",id).eq("user_id",s.user.id):db.from("post_reactions").insert({post_id:id,user_id:s.user.id,reaction:"like"});const {error}=await q;if(error)msg(error.message,"error");else loadFeed(document.querySelector("[data-feed]"))}
async function comment(id,form){const s=await session();if(!s){location.hash="content/login.html";return}const input=form.querySelector("input");const content=input.value.trim();if(!content)return;const {error}=await db.from("comments").insert({post_id:id,user_id:s.user.id,content});if(error)msg(error.message,"error");else{input.value="";loadFeed(document.querySelector("[data-feed]"))}}
async function rsvp(id){const s=await session();if(!s){location.hash="content/login.html";return}const {data}=await db.from("event_rsvps").select("status").eq("event_id",id).eq("user_id",s.user.id).maybeSingle();const status=data?.status==="going"?"interested":"going";const q=data?db.from("event_rsvps").update({status}).eq("event_id",id).eq("user_id",s.user.id):db.from("event_rsvps").insert({event_id:id,user_id:s.user.id,status});const {error}=await q;if(error)msg(error.message,"error");else loadEvents(document.querySelector("[data-events]"))}
async function report(id){const s=await session();if(!s){location.hash="content/login.html";return}const reason=prompt("Why are you reporting this post?");if(!reason)return;const {error}=await db.from("reports").insert({reporter_id:s.user.id,post_id:id,reason});if(error)msg(error.message,"error");else msg("Report submitted for review.","success")}
async function newEvent(){const s=await session();if(!s){location.hash="content/login.html";return}const title=prompt("Event title");if(!title)return;const date=prompt("Start date/time (e.g. 2026-12-01T18:00)");if(!date)return;const description=prompt("Description (optional)")||"";const location=prompt("Location (optional)")||"";const {error}=await db.from("events").insert({creator_id:s.user.id,title,description,location,starts_at:new Date(date).toISOString()});if(error)msg(error.message,"error");else loadEvents(document.querySelector("[data-events]"))}

async function uploadFiles(files){const s=await session();if(!s){location.hash="content/login.html";return}for(const file of files){const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_");const path=s.user.id+"/"+Date.now()+"-"+safe;const up=await db.storage.from("community-media").upload(path,file,{upsert:false,contentType:file.type});if(up.error){msg(up.error.message,"error");continue}const u=db.storage.from("community-media").getPublicUrl(path);const type=file.type.startsWith("video/")?"video":"image";const ins=await db.from("Media").insert({user_id:s.user.id,title:file.name,media_type:type,mime_type:file.type,file_size:file.size,media_url:u.data.publicUrl}).select("id").single();if(ins.error)msg(ins.error.message,"error")}await loadGallery(document.querySelector("[data-gallery]"))}
async function createAlbum(){const s=await session();if(!s){location.hash="content/login.html";return}const name=prompt("Album name");if(!name)return;const r=await db.from("Album").insert({user_id:s.user.id,name,visibility:"public"});if(r.error)msg(r.error.message,"error");else msg("Album created.","success")}
async function savePreferences(){const s=await session();if(!s){msg("Sign in to save preferences.","error");return}const v={user_id:s.user.id,language:document.querySelector("[data-language]").value,theme_mode:document.querySelector("[data-theme-mode]").value,theme_preset:document.querySelector("[data-theme-preset]").value};const r=await db.from("user_preferences").upsert(v);if(r.error)msg(r.error.message,"error");else{document.documentElement.dataset.themeMode=v.theme_mode;document.documentElement.dataset.themePreset=v.theme_preset}}
async function loadPreferences(){const s=await session();const p=document.querySelector("[data-theme-preset]"),m=document.querySelector("[data-theme-mode]"),l=document.querySelector("[data-language]");const t=await db.from("theme_presets").select("key,name").eq("is_active",true).order("name");p.innerHTML=(t.data||[]).map(x=>'<option value="'+esc(x.key)+'">'+esc(x.name)+'</option>').join("");if(s){const r=await db.from("user_preferences").select("language,theme_mode,theme_preset").eq("user_id",s.user.id).maybeSingle();if(r.data){l.value=r.data.language;m.value=r.data.theme_mode;p.value=r.data.theme_preset;document.documentElement.dataset.themeMode=r.data.theme_mode;document.documentElement.dataset.themePreset=r.data.theme_preset}}l.onchange=savePreferences;m.onchange=savePreferences;p.onchange=savePreferences}

async function editPost(id){const s=await session();if(!s)return;const r=await db.from("posts").select("content").eq("id",id).eq("user_id",s.user.id).single();const content=prompt("Edit post",r.data?.content||"");if(content===null)return;const u=await db.from("posts").update({content:content.trim()}).eq("id",id).eq("user_id",s.user.id);if(u.error)msg(u.error.message,"error");else loadFeed(document.querySelector("[data-feed]"))}
async function deletePost(id){const s=await session();if(!s||!confirm("Delete this post?"))return;const r=await db.from("posts").delete().eq("id",id).eq("user_id",s.user.id);if(r.error)msg(r.error.message,"error");else loadFeed(document.querySelector("[data-feed]"))}
export async function initCommunity(){if(!db)return;const feed=document.querySelector("[data-feed]");if(!feed)return;document.querySelector("[data-create-post]")?.addEventListener("click",createPost);document.querySelector("[data-refresh-feed]")?.addEventListener("click",()=>loadFeed(feed));document.querySelector("[data-new-event]")?.addEventListener("click",newEvent);document.querySelector("[data-create-album]")?.addEventListener("click",createAlbum);document.querySelector("[data-media-files]")?.addEventListener("change",e=>document.querySelector("[data-selected-media]").textContent=e.target.files.length?e.target.files.length+" file(s) selected":"No media selected");document.querySelector("[data-gallery-upload]")?.addEventListener("change",e=>uploadFiles([...e.target.files]));document.querySelectorAll("[data-community-tab]").forEach(b=>b.addEventListener("click",async()=>{document.querySelectorAll("[data-community-tab]").forEach(x=>x.classList.toggle("is-active",x===b));document.querySelectorAll("[data-community-view]").forEach(x=>x.hidden=x.dataset.communityView!==b.dataset.communityTab);if(b.dataset.communityTab==="members")loadMembers(document.querySelector("[data-members]"));if(b.dataset.communityTab==="events")loadEvents(document.querySelector("[data-events]"));if(b.dataset.communityTab==="gallery")loadGallery(document.querySelector("[data-gallery]"));if(b.dataset.communityTab==="settings")loadPreferences();}));document.addEventListener("click",e=>{const like=e.target.closest("[data-like]"),toggle=e.target.closest("[data-comments]"),rep=e.target.closest("[data-report]"),rv=e.target.closest("[data-rsvp]"),edit=e.target.closest("[data-edit-post]"),del=e.target.closest("[data-delete-post]");if(like)react(like.dataset.like);if(rep)report(rep.dataset.report);if(rv)rsvp(rv.dataset.rsvp);if(edit)editPost(edit.dataset.editPost);if(del)deletePost(del.dataset.deletePost);if(toggle){const box=document.querySelector('[data-comments-box="'+toggle.dataset.comments+'"]');if(box)box.hidden=!box.hidden}});document.addEventListener("submit",e=>{const f=e.target.closest("[data-comment-form]");if(f){e.preventDefault();comment(f.dataset.commentForm,f)}});await Promise.all([loadFeed(feed),loadAnnouncements(document.querySelector("[data-announcements]")),loadEvents(document.querySelector("[data-event-preview]"))]);}