// Central application loader.
import { initContent } from "./context/content.js";
const globalStylesheet="./style/global-style.css";
const pageStylesheet="./style/page-style.css";
const communityStylesheet="./style/community.css";
const cardStylesheet="./component/cards/cards.css";
const contextFiles=[{name:"header",html:"./context/header.html",css:"./context/header.css"},{name:"sidebar",html:"./context/sidebar.html",css:"./context/sidebar.css"},{name:"content",html:"./context/content.html",css:"./context/content.css"}];
const contextLayoutStylesheet="./context/layout.css";
const pageFiles={"content/home.html":"./content/home.html","content/login.html":"./content/login.html","content/create-account.html":"./content/create-account.html","content/forgot-password.html":"./content/forgot-password.html","content/profile.html":"./content/profile.html","content/community.html":"./content/community.html"};
const componentFiles={avatar:{html:"./component/avatar/avatar.html",css:"./component/avatar/avatar.css",js:"./component/avatar/avatar.js"},menu:{html:"./component/menu/menu.html",css:"./component/menu/menu.css",js:"./component/menu/menu.js"},search:{html:"./component/search/search.html",css:"./component/search/search.css",js:"./component/search/search.js"},language:{html:"./component/language/language.html",css:"./component/language/language.css",js:"./component/language/language.js"}};
const componentTemplateCache=new Map();
function loadStylesheet(href){return new Promise((resolve,reject)=>{if(document.querySelector(`link[href="${href}"]`))return resolve();const link=document.createElement("link");link.rel="stylesheet";link.href=href;link.onload=resolve;link.onerror=()=>reject(new Error(`Failed to load ${href}`));document.head.appendChild(link);});}
async function loadContextFile(file){const [response]=await Promise.all([fetch(file.html),loadStylesheet(file.css)]);if(!response.ok)throw new Error(`Failed to load ${file.html}: ${response.status}`);return{name:file.name,html:await response.text()};}
async function loadComponentTemplate(name){if(componentTemplateCache.has(name))return componentTemplateCache.get(name);const component=componentFiles[name];if(!component)throw new Error(`Unknown component: ${name}`);const [response]=await Promise.all([fetch(component.html),loadStylesheet(component.css)]);if(!response.ok)throw new Error(`Failed to load ${component.html}: ${response.status}`);const html=await response.text();componentTemplateCache.set(name,html);return html;}
async function mountComponents(root){const placeholders=[...root.querySelectorAll("[data-component]")];await Promise.all(placeholders.map(async placeholder=>{const name=placeholder.dataset.component;if(!componentFiles[name])return;try{placeholder.outerHTML=await loadComponentTemplate(name)}catch(error){console.error(`Component mount failed: ${name}`,error)}}))}
async function initializeComponents(root){await mountComponents(root);const modules=await Promise.all(Object.entries(componentFiles).filter(([name])=>componentFiles[name].js&&root.querySelector(`[data-${name}]`)).map(([,component])=>import(component.js)));for(const module of modules){if(module.initMenu)module.initMenu(root);if(module.initSearch)module.initSearch(root);if(module.initAvatar)module.initAvatar(root);if(module.initLanguage)module.initLanguage(root);}}
function updateActiveRoutes(path){document.querySelectorAll("[data-route]").forEach(link=>{const active=link.dataset.route===path;active?link.setAttribute("aria-current","page"):link.removeAttribute("aria-current")})}
function showLoaderError(message){const content=initContent();if(content)content.innerHTML=`<section class="page page-error"><div class="card"><h1>Something went wrong</h1><p>We couldn't load this page. Please try again.</p><p class="form-message">${message}</p></div></section>`}
async function requireRouteAccess(path){const access=window.dalimgariAccess;if(!access?.enforceRoute)return true;const result=await access.enforceRoute(path);if(result.allowed)access.applyElementAccess(document,result.context);return result.allowed}
async function loadPage(path){const content=initContent();const pagePath=pageFiles[path]||pageFiles["content/home.html"];if(!content)throw new Error("Missing content container");if(!(await requireRouteAccess(pagePath)))return;await loadStylesheet(pagePath==="content/community.html"?communityStylesheet:pageStylesheet);const response=await fetch(pagePath);if(!response.ok)throw new Error(`Failed to load page: ${response.status}`);content.innerHTML=await response.text();await initializeComponents(content);const access=window.dalimgariAccess;if(access?.getContext)access.applyElementAccess(content,await access.getContext());if(window.dalimgariLanguage?.applyLanguage)window.dalimgariLanguage.applyLanguage(content);if(pagePath==="content/community.html"){const {initCommunity}=await import("./supabase/community.js");await initCommunity()}updateActiveRoutes(pagePath);document.dispatchEvent(new CustomEvent("dalimgari:page-loaded",{detail:{path:pagePath}}))}
function bindRoutes(){document.addEventListener("click",event=>{const link=event.target.closest("[data-route]");if(!link)return;const path=link.dataset.route;if(!pageFiles[path])return;event.preventDefault();if(window.location.hash!==`#${path}`)window.location.hash=path;else loadPage(path).catch(error=>showLoaderError(error.message))});window.addEventListener("hashchange",()=>{const path=window.location.hash.slice(1)||"content/home.html";loadPage(path).catch(error=>showLoaderError(error.message))})}
async function initializeWebsite(){const app=document.getElementById("app");if(!app)throw new Error("Missing root element: #app");await import("./supabase/auth/access.js");const languageModule=await import("./component/language/language.js");window.dalimgariLanguage=languageModule;await loadStylesheet(globalStylesheet);await loadStylesheet(pageStylesheet);await loadStylesheet(cardStylesheet);await loadStylesheet(contextLayoutStylesheet);const loaded=await Promise.all(contextFiles.map(loadContextFile));const context=document.createElement("div");context.id="context";const sections=new Map();for(const file of loaded){const section=document.createElement("section");section.dataset.context=file.name;section.innerHTML=file.html;sections.set(file.name,section)}const layout=document.createElement("div");layout.className="site-layout";layout.append(sections.get("sidebar"),sections.get("content"));context.append(sections.get("header"),layout);app.replaceChildren(context);await initializeComponents(context);bindRoutes();await loadPage(window.location.hash.slice(1)||"content/home.html")}
initializeWebsite().catch(error=>showLoaderError(error.message));