import { supabase } from '../lib/supabase'
const cache = new Map()
export const GLOBAL_LABEL_DEFAULTS={menu:'Menu',login:'Login',back:'Back',search:'Search',home:'Home',close:'Close',profile:'Profile',information:'Information',posts:'Posts',post:'Post',albums:'Albums',album:'Album',gallery:'Gallery',notice:'Notice',events:'Events',members:'Members',contact:'Contact',settings:'Settings',notifications:'Notifications',messages:'Messages',comments:'Comments',photos:'Photos',videos:'Videos',documents:'Documents',help:'Help',about:'About',language:'Language',bengali:'Bengali',english:'English',day:'Day',night:'Night',logout:'Logout',save:'Save',edit:'Edit',delete:'Delete',add:'Add',remove:'Remove',share:'Share',download:'Download',upload:'Upload',refresh:'Refresh',loading:'Loading',dashboard:'Dashboard',admin:'Admin',user:'User',key_label_management:'Key Label Management',key_label_rename:'Key Label Rename',key_name:'Key Name',english_label:'English Label',bangla_label:'Bangla Label'}
export async function getGlobalLabels(){if(!supabase)return{};await Promise.all(Object.entries(GLOBAL_LABEL_DEFAULTS).map(([key,eng])=>ensureGlobalLabel(key,eng).catch(()=>null)));const {data,error}=await supabase.from('global_ui_labels').select('key,eng,bng');if(error)throw error;const labels={};for(const row of data||[]){labels[row.key]={eng:row.eng,bng:row.bng||null};cache.set(row.key,labels[row.key])}return labels}
export async function listGlobalLabels(){if(!supabase)throw new Error('Supabase is not configured');const {data,error}=await supabase.from('global_ui_labels').select('key,eng,bng').order('key',{ascending:true});if(error)throw error;return data||[]}
export function label(key,language='bng',fallback=key){const item=cache.get(key);if(!item)return fallback;return language==='eng'?(item.eng||fallback):(item.bng||fallback)}
export async function ensureGlobalLabel(key,eng){if(!supabase||!key||!eng)return null;const {data,error}=await supabase.rpc('ensure_global_ui_label',{p_key:key,p_eng:eng});if(error)throw error;const row=Array.isArray(data)?data[0]:data;if(row)cache.set(key,{eng:row.eng,bng:row.bng||null});return row}
export async function updateGlobalLabel(key,eng,bng){if(!supabase)throw new Error('Supabase is not configured');const english=String(eng??'').trim();const bangla=String(bng??'').trim()||null;if(!english)throw new Error('English label is required');const {data,error}=await supabase.from('global_ui_labels').update({eng:english,bng:bangla}).eq('key',key).select('key,eng,bng').single();if(error)throw error;cache.set(key,{eng:data.eng,bng:data.bng||null});return data}
export function clearGlobalLabelCache(){cache.clear()}
