import PROJECT_PATHS, { projectPathBasename } from '../src/config/projectPaths.js'
import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'

const root = process.cwd()
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8')

test('Master Specification: no Firebase dependency or source reference', () => {
  const packageJson = read(PROJECT_PATHS.package)
  assert.doesNotMatch(packageJson, /firebase/i)
})

test('Master Specification: media storage restrictions are reproducible', () => {
  const migrations = fs.readdirSync(path.join(root, 'supabase/migrations'))
  const hardening = migrations.find((name) => name === '20261001201247_harden_media_storage_and_rbac_policies.sql')
  assert.ok(hardening)
  const sql = read(PROJECT_PATHS.migrations.mediaHardening)
  assert.match(sql, /file_size_limit = 52428800/)
  assert.match(sql, /allowed_mime_types/)
  assert.match(sql, /current_user_has_permission\('media_manage'\)/)
})

test('Master Specification: production workflow uses Node 22 and Pages fallback', () => {
  const workflow = read(PROJECT_PATHS.workflows.deploy)
  assert.match(workflow, /node-version:\s*['\"]?22/i)
  assert.match(workflow, /cp dist\/index\.html dist\/404\.html/)
})

test('Master Specification: migration directory contains no known invalid schema references', () => {
  const migrations = fs.readdirSync(path.join(root, 'supabase/migrations'))
  assert.ok(!migrations.some((name) => name.includes('spec_integrity_guards')))
  assert.ok(!migrations.some((name) => name.includes('spec_public_lookup_guards')))
  assert.ok(!migrations.some((name) => name.includes('migration_drift_guard')))
})

test('Master Specification: media source matrix is covered end-to-end', () => {
  const management = read(PROJECT_PATHS.pages.mediaManagement)
  const service = read(PROJECT_PATHS.services.media)
  const renderer = read(PROJECT_PATHS.components.ui.mediaContent)
  const albumPage = read(PROJECT_PATHS.pages.albums)
  const postPage = read(PROJECT_PATHS.pages.postDetail)

  assert.match(management, /type="file"/)
  assert.match(management, /image\/\*,video\/\*,audio\/\*,application\/pdf/)
  assert.match(management, /value: 'image'/)
  assert.match(management, /value: 'video'/)
  assert.match(management, /value: 'audio'/)
  assert.match(management, /value: 'document'/)
  assert.match(management, /createMediaRecord/)
  assert.match(management, /createExternalMediaRecord/)
  assert.match(service, /storage_path: storagePath/)
  assert.match(service, /media_url: normalizedUrl/)
  assert.match(service, /audio\/external/)
  assert.match(service, /application\/pdf/)
  assert.match(renderer, /<img/)
  assert.match(renderer, /<video/)
  assert.match(renderer, /<audio/)
  assert.match(renderer, /<iframe/)
  assert.match(renderer, /media-file-link/)
  assert.match(albumPage, /<MediaContent/)
  assert.match(postPage, /<MediaContent/)
})

test('Key Label Management: search and edit are scoped to global_ui_labels', () => {
  const page = read(PROJECT_PATHS.pages.keyLabelManagement)
  const service = read(PROJECT_PATHS.services.globalLabel)
  const app = read(PROJECT_PATHS.app.entry)
  const migrations = fs.readdirSync(path.join(root, 'supabase/migrations'))
  const labelsMigration = migrations.find((name) => name === '20261001220445_create_global_ui_labels.sql')

  assert.match(page, /listGlobalLabels\(\)/)
  assert.match(page, /row\.key/)
  assert.doesNotMatch(page, /row\.eng/)
  assert.match(page, /row\.bng/)
  assert.match(page, /updateGlobalLabel\(/)
  assert.match(page, /readOnly/)
  assert.match(service, /from\('global_ui_labels'\)/)
  assert.match(service, /select\('key,bng'\)/)
  assert.match(app, /\/admin\/key-labels/)
  assert.match(page, /লেবেল ব্যবস্থাপনা/)
  assert.ok(labelsMigration)
  const singleLanguageMigration = migrations.find((name) => name === '20261003110000_single_language_global_ui_labels.sql')
  assert.ok(singleLanguageMigration)
  assert.match(read(PROJECT_PATHS.migrations.singleLanguageGlobalUiLabels), /drop column if exists eng/)
  assert.match(read(PROJECT_PATHS.migrations.globalUiLabels), /global_ui_labels/)
})


test('Language switch: Bengali remains canonical and English is runtime translation only', () => {
  const preferences = read(PROJECT_PATHS.context.preferences)
  const header = read(PROJECT_PATHS.header.component)
  const sidebar = read(PROJECT_PATHS.sidebar.component)
  const runtime = read(PROJECT_PATHS.services.languageRuntime)
  const labelsService = read(PROJECT_PATHS.services.globalLabel)
  const banner = read(PROJECT_PATHS.components.website.banner)
  const information = read(PROJECT_PATHS.pages.information)

  assert.match(preferences, /DEFAULT_LANGUAGE = 'bng'/)
  const devicePreferences = read(PROJECT_PATHS.services.devicePreference)
  assert.match(preferences, /getLanguagePreference\(\)/)
  assert.match(preferences, /saveLanguagePreference\(value\)/)
  assert.match(devicePreferences, /dalimgari_language_preference/)
  assert.match(devicePreferences, /saved === 'eng' \|\| saved === 'bng'/)
  assert.match(devicePreferences, /localStorage\.setItem/)
  assert.doesNotMatch(header, /data-language-switch/)
  assert.doesNotMatch(header, /site-header__language-switch/)
  assert.match(sidebar, /language === 'bng' \? 'English' : 'বাংলা'/)
  assert.match(sidebar, /setLanguagePreference\(language === 'bng' \? 'eng' : 'bng'\)/)
  assert.match(runtime, /translateWithOverrides/)
  assert.match(runtime, /loadTranslationOverrides/)
  assert.match(runtime, /translationOverrides\.get\(normalizedSource\)/)
  assert.doesNotMatch(runtime, /data-no-translate/)
  assert.doesNotMatch(runtime, /data-translation-override-only/)
  assert.doesNotMatch(runtime, /allowAutomatic = true/)
  assert.match(runtime, /document\.documentElement\.lang = isEnglish \? 'en' : 'bn'/)
  assert.match(runtime, /restoreDocument\(document\.body\)/)
  assert.match(labelsService, /select\('key,bng'\)/)
  assert.doesNotMatch(labelsService, /select\('key,eng,bng'\)/)
  assert.doesNotMatch(banner, /data-translation-override-only/)
  assert.doesNotMatch(information, /data-translation-override-only/)
  const overrideService = read(PROJECT_PATHS.services.translationOverride)
  const overridePage = read(PROJECT_PATHS.pages.translationOverrideManagement)
  const app = read(PROJECT_PATHS.app.entry)
  const adminLayout = read(PROJECT_PATHS.components.admin.adminLayout)
  assert.match(overrideService, /from\('translation_overrides'\)/)
  assert.match(overrideService, /upsert/)
  assert.match(overridePage, /বাংলা source/)
  assert.match(overridePage, /নির্ধারিত English/)
  assert.match(app, /\/manage\/translation-overrides/)
  assert.match(adminLayout, /translation_overrides/)
  const overrideMigration = fs.readdirSync(path.join(root, 'supabase/migrations')).find((name) => name === '20261003123000_create_translation_overrides.sql')
  assert.ok(overrideMigration)
  assert.match(read(PROJECT_PATHS.migrations.translationOverrides), /translation_overrides/)
  const publicOverrideMigration = fs.readdirSync(path.join(root, 'supabase/migrations')).find((name) => name === '20261003140000_make_translation_overrides_public_equal.sql')
  assert.ok(publicOverrideMigration)
  const publicOverrideSql = read(PROJECT_PATHS.migrations.publicTranslationOverrides)
  assert.match(publicOverrideSql, /for select/i)
  assert.match(publicOverrideSql, /for insert/i)
  assert.match(publicOverrideSql, /for update/i)
  assert.match(publicOverrideSql, /for delete/i)
  assert.match(publicOverrideSql, /to public/i)
})
