import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'

const root = process.cwd()
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8')

test('Master Specification: no Firebase dependency or source reference', () => {
  const packageJson = read('package.json')
  assert.doesNotMatch(packageJson, /firebase/i)
})

test('Master Specification: media storage restrictions are reproducible', () => {
  const migrations = fs.readdirSync(path.join(root, 'supabase/migrations'))
  const hardening = migrations.find((name) => name === '20261001201247_harden_media_storage_and_rbac_policies.sql')
  assert.ok(hardening)
  const sql = read(`supabase/migrations/${hardening}`)
  assert.match(sql, /file_size_limit = 52428800/)
  assert.match(sql, /allowed_mime_types/)
  assert.match(sql, /current_user_has_permission\('media_manage'\)/)
})

test('Master Specification: production workflow uses Node 22 and Pages fallback', () => {
  const workflow = read('.github/workflows/deploy.yml')
  assert.match(workflow, /node-version:\s*['\"]?22/i)
  assert.match(workflow, /cp dist\/index\.html dist\/404\.html/)
})

test('Master Specification: migration directory contains no known invalid schema references', () => {
  const migrations = fs.readdirSync(path.join(root, 'supabase/migrations'))
  assert.ok(!migrations.some((name) => name.includes('spec_integrity_guards')))
  assert.ok(!migrations.some((name) => name.includes('spec_public_lookup_guards')))
  assert.ok(!migrations.some((name) => name.includes('migration_drift_guard')))
})

test('Master Specification: media source matrix is covered end-to-end', () => {
  const management = read('src/pages/admin/MediaManagement.jsx')
  const service = read('src/services/mediaService.js')
  const renderer = read('src/components/ui/MediaContent.jsx')
  const albumPage = read('src/pages/Albums.jsx')
  const postPage = read('src/pages/PostDetail.jsx')

  assert.match(management, /type="file"/)
  assert.match(management, /image\/\*,video\/\*,audio\/\*,application\/pdf/)
  assert.match(management, /value: 'image'/)
  assert.match(management, /value: 'video'/)
  assert.match(management, /value: 'audio'/)
  assert.match(management, /value: 'document'/)
  assert.match(management, /createMediaRecord/)
  assert.match(management, /createExternalMediaRecord/)
  assert.match(service, /storage_path: storagePath/)
  assert.match(service, /media_url: normalizedUrl/)
  assert.match(service, /audio\/external/)
  assert.match(service, /application\/pdf/)
  assert.match(renderer, /<img/)
  assert.match(renderer, /<video/)
  assert.match(renderer, /<audio/)
  assert.match(renderer, /<iframe/)
  assert.match(renderer, /media-file-link/)
  assert.match(albumPage, /<MediaContent/)
  assert.match(postPage, /<MediaContent/)
})

test('Key Label Management: search and edit are scoped to global_ui_labels', () => {
  const page = read('src/pages/admin/KeyLabelManagement.jsx')
  const service = read('src/services/globalLabelService.js')
  const app = read('src/App.jsx')
  const migrations = fs.readdirSync(path.join(root, 'supabase/migrations'))
  const labelsMigration = migrations.find((name) => name === '20261001220445_create_global_ui_labels.sql')

  assert.match(page, /listGlobalLabels\(\)/)
  assert.match(page, /row\.key/)
  assert.doesNotMatch(page, /row\.eng/)
  assert.match(page, /row\.bng/)
  assert.match(page, /updateGlobalLabel\(/)
  assert.match(page, /readOnly/)
  assert.match(service, /from\('global_ui_labels'\)/)
  assert.match(service, /select\('key,bng'\)/)
  assert.match(app, /\/admin\/key-labels/)
  assert.match(page, /লেবেল ব্যবস্থাপনা/)
  assert.ok(labelsMigration)
  const singleLanguageMigration = migrations.find((name) => name === '20261003110000_single_language_global_ui_labels.sql')
  assert.ok(singleLanguageMigration)
  assert.match(read(`supabase/migrations/${singleLanguageMigration}`), /drop column if exists eng/)
  assert.match(read(`supabase/migrations/${labelsMigration}`), /global_ui_labels/)
})


test('Language switch: Bengali remains canonical and English is runtime translation only', () => {
  const preferences = read('src/context/PreferencesContext.jsx')
  const header = read('src/components/layout/Header.jsx')
  const sidebar = read('src/components/layout/Sidebar.jsx')
  const runtime = read('src/services/languageRuntime.js')
  const labelsService = read('src/services/globalLabelService.js')
  const banner = read('src/components/website/Banner.jsx')
  const information = read('src/pages/Information.jsx')

  assert.match(preferences, /DEFAULT_LANGUAGE = 'bng'/)
  const devicePreferences = read('src/services/devicePreferenceService.js')
  assert.match(preferences, /getLanguagePreference\(\)/)
  assert.match(preferences, /saveLanguagePreference\(value\)/)
  assert.match(devicePreferences, /dalimgari_language_preference/)
  assert.match(devicePreferences, /saved === 'eng' \|\| saved === 'bng'/)
  assert.match(devicePreferences, /localStorage\.setItem/)
  assert.doesNotMatch(header, /data-language-switch/)
  assert.doesNotMatch(header, /site-header__language-switch/)
  assert.match(sidebar, /language === 'bng' \? 'English' : 'বাংলা'/)
  assert.match(sidebar, /setLanguagePreference\(language === 'bng' \? 'eng' : 'bng'\)/)
  assert.match(runtime, /translateWithOverrides/)
  assert.match(runtime, /loadTranslationOverrides/)
  assert.match(runtime, /translationOverrides\.get\(normalizedSource\)/)
  assert.match(runtime, /element\.closest\('\[data-no-translate\]'\)/)
  assert.match(runtime, /data-translation-override-only/)
  assert.match(runtime, /allowAutomatic = true/
  assert.match(runtime, /document\.documentElement\.lang = isEnglish \? 'en' : 'bn'/)
  assert.match(runtime, /restoreDocument\(document\.body\)/)
  assert.match(labelsService, /select\('key,bng'\)/)
  assert.doesNotMatch(labelsService, /select\('key,eng,bng'\)/)
  assert.match(banner, /data-translation-override-only="true"/
  assert.match(information, /data-translation-override-only=.*village_name/)
  const overrideService = read('src/services/translationOverrideService.js')
  const overridePage = read('src/pages/admin/TranslationOverrideManagement.jsx')
  const app = read('src/App.jsx')
  const adminLayout = read('src/components/admin/AdminLayout.jsx')
  assert.match(overrideService, /from\('translation_overrides'\)/)
  assert.match(overrideService, /upsert/)
  assert.match(overridePage, /বাংলা source/)
  assert.match(overridePage, /নির্ধারিত English/)
  assert.match(app, /\/manage\/translation-overrides/)
  assert.match(adminLayout, /translation_overrides/)
  const overrideMigration = fs.readdirSync(path.join(root, 'supabase/migrations')).find((name) => name === '20261003123000_create_translation_overrides.sql')
  assert.ok(overrideMigration)
  assert.match(read(`supabase/migrations/${overrideMigration}`), /translation_overrides/)
})
