import {getPlatformContext} from "../../context/platform.js";
const months=["Boishakh","Joishtho","Ashar","Srabon","Bhadro","Ashwin","Kartik","Agrahayan","Poush","Magh","Falgun","Chaitra"];
const bnMonths=["বৈশাখ","জ্যৈষ্ঠ","আষাঢ়","শ্রাবণ","ভাদ্র","আশ্বিন","কার্তিক","অগ্রহায়ণ","পৌষ","মাঘ","ফাল্গুন","চৈত্র"];
const bnWeekdays=["রবিবার","সোমবার","মঙ্গলবার","বুধবার","বৃহস্পতিবার","শুক্রবার","শনিবার"];
const enWeekdays=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
const toBn=s=>String(s).replace(/\\d/g,d=>"০১২৩৪৫৬৭৮৯"[d]);
function banglaDate(date){const y=date.getUTCFullYear(),m=date.getUTCMonth(),day=date.getUTCDate(),start=new Date(Date.UTC(y,3,14));let by=y-593;if(date<start)by=y-594;let days=Math.floor((date-start)/86400000);if(days<0){const prevStart=new Date(y-1,3,14);days=Math.floor((date-prevStart)/86400000);};const lengths=[31,31,31,31,31,31,30,30,30,30,(((m>=3?y+1:y)%4===0&&((m>=3?y+1:y)%100!==0||(m>=3?y+1:y)%400===0))?30:29),30];let month=0;while(days>=lengths[month]&&month<11){days-=lengths[month++]}return{year:by,month,day:days+1};}
function formatTime(date,lang){const h=date.getHours(),minute=String(date.getMinutes()).padStart(2,"0");if(lang==="bn"){const hour=h%12||12;const period=h<12?"সকাল":h<17?"বিকেল":h<20?"সন্ধ্যা":"রাত";return `${toBn(hour)}:${toBn(minute)} ${period}`}return new Intl.DateTimeFormat("en-US",{timeZoneName:"short",hour:"numeric",minute:"2-digit",hour12:true}).format(date)}
function render(root,ctx){const lang=document.documentElement.lang==="bn"?"bn":"en";const tz=ctx.community.timezone||"Asia/Dhaka";const now=new Date();const parts=new Intl.DateTimeFormat("en-US",{timeZone:tz,year:"numeric",month:"numeric",day:"numeric",weekday:"long",hour:"numeric",minute:"numeric",second:"numeric",hour12:false}).formatToParts(now);const get=t=>Number(parts.find(x=>x.type===t)?.value);const local=new Date(Date.UTC(get("year"),get("month")-1,get("day"),get("hour"),get("minute"),get("second")));const bd=banglaDate(local);const greg=new Intl.DateTimeFormat(lang==="bn"?"bn-BD":"en-US",{timeZone:tz,year:"numeric",month:"long",day:"numeric"}).format(now);const primary=lang==="bn"?`${toBn(bd.day)} ${bnMonths[bd.month]} ${toBn(bd.year)}`:greg;const secondary=lang==="bn"?greg:`${bd.day} ${months[bd.month]} ${bd.year}`;root.querySelector("[data-date-primary]").textContent=primary;root.querySelector("[data-date-secondary]").textContent=secondary;root.querySelector("[data-time]").textContent=formatTime(now,lang);root.querySelector("[data-weekday]").textContent=lang==="bn"?bnWeekdays[local.getUTCDay()]:enWeekdays[local.getUTCDay()];root.querySelector("[data-timezone]").textContent=ctx.community.timezone||"—"}
export async function initDateTime(root=document){const el=root.querySelector("[data-date-time]");if(!el)return;const ctx=await getPlatformContext();const tick=()=>render(el,ctx);tick();const timer=setInterval(tick,1000);document.addEventListener("dalimgari:language-changed",tick);window.addEventListener("beforeunload",()=>clearInterval(timer),{once:true})}
