const db=window.dalimgariSupabase;
const esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const dateText=v=>{try{return new Intl.DateTimeFormat(document.documentElement.lang==="bn"?"bn-BD":"en-US",{day:"numeric",month:"short"}).format(new Date(v))}catch{return ""}};
export async function initHome(root=document){const page=root.querySelector("[data-page=home]");if(!page||!db)return;
const media=await db.from("Media").select("id,title,description,media_url,thumbnail_url,media_type,created_at").eq("visibility","public").order("created_at",{ascending:false}).limit(8);
const items=media.data||[];const hero=page.querySelector("[data-home-feature]");const first=items.find(x=>x.media_type==="image");if(hero&&first)hero.innerHTML='<img src="'+esc(first.thumbnail_url||first.media_url)+'" alt="'+esc(first.title)+'">';
const grid=page.querySelector("[data-home-media]");if(grid)grid.innerHTML=items.map(x=>'<article class="home-media-card">'+(x.media_type==="video"?'<video muted playsinline preload="metadata" src="'+esc(x.media_url)+'"></video>':'<img loading="lazy" src="'+esc(x.thumbnail_url||x.media_url)+'" alt="'+esc(x.title)+'">')+'<div class="home-media-card__label"><strong>'+esc(x.title)+'</strong></div></article>').join("")||'<div class="empty">No media yet.</div>';
const ev=await db.from("events").select("title,description,location,starts_at").order("starts_at",{ascending:true}).limit(3);const ep=page.querySelector("[data-home-events]");if(ep)ep.innerHTML=(ev.data||[]).map(x=>'<div class="home-list-item"><strong>'+esc(x.title)+'</strong><small>'+dateText(x.starts_at)+(x.location?" · "+esc(x.location):"")+'</small></div>').join("")||'<div class="empty">No upcoming events.</div>';
const an=await db.from("announcements").select("title,content,created_at").eq("published",true).order("created_at",{ascending:false}).limit(3);const ap=page.querySelector("[data-home-announcements]");if(ap)ap.innerHTML=(an.data||[]).map(x=>'<div class="home-list-item"><strong>'+esc(x.title)+'</strong><small>'+esc(x.content)+'</small></div>').join("")||'<div class="empty">No announcements yet.</div>';}
