const supabaseClient=window.dalimgariSupabase;
function authMessage(form,message,type="info"){const output=form.querySelector("[data-auth-message]");if(!output)return;output.textContent=message;output.dataset.state=type;}
function setFormBusy(form,busy,label){form.setAttribute("aria-busy",String(busy));form.querySelectorAll("button,input").forEach(control=>control.disabled=busy);if(busy&&form.querySelector("button[type=submit]"))form.querySelector("button[type=submit]").dataset.originalLabel=form.querySelector("button[type=submit]").textContent;if(form.querySelector("button[type=submit]"))form.querySelector("button[type=submit]").textContent=busy?label:(form.querySelector("button[type=submit]").dataset.originalLabel||form.querySelector("button[type=submit]").textContent);}
function getAppBaseUrl(){return new URL("./",window.location.href).href}
function goToContent(path){if(window.location.hash===`#${path}`){window.dispatchEvent(new HashChangeEvent("hashchange"));return}window.location.hash=path}
function updateAuthUI(session){document.querySelectorAll("[data-avatar]").forEach(avatar=>{const signedIn=Boolean(session);const path=signedIn?"content/profile.html":"content/login.html";avatar.href=`#${path}`;avatar.dataset.route=path;avatar.setAttribute("aria-label",signedIn?"Profile":"Sign in")});}
async function getSession(){if(!supabaseClient)return null;const {data,error}=await supabaseClient.auth.getSession();if(error)throw error;return data.session}
async function loadProfile(session){if(!session||!supabaseClient)return null;const {data,error}=await supabaseClient.from("User").select("username,email,avatar_url,account_status,account_type,role_id").eq("user_id",session.user.id).maybeSingle();if(error)throw error;if(!data)return null;let role=null;let permissions=[];if(data.role_id){const roleResult=await supabaseClient.from("Role").select("name,permission_ids").eq("id",data.role_id).maybeSingle();if(roleResult.error)throw roleResult.error;role=roleResult.data?.name||null;const ids=Array.isArray(roleResult.data?.permission_ids)?roleResult.data.permission_ids:[];if(ids.length){const permissionResult=await supabaseClient.from("Permission").select("key").in("id",ids);if(permissionResult.error)throw permissionResult.error;permissions=(permissionResult.data||[]).map(item=>item.key).filter(Boolean)}}return{...data,role_name:role,permissions}}
async function refreshAuthUI(){try{const session=await getSession();updateAuthUI(session);const page=document.querySelector('[data-page="profile"]');if(page&&session){const profile=await loadProfile(session);page.querySelector("[data-profile-username]").textContent=profile?.username||session.user.user_metadata?.name||"—";page.querySelector("[data-profile-email]").textContent=profile?.email||session.user.email||"—";page.querySelector("[data-profile-status]").textContent=profile?.account_status||"active";page.querySelector("[data-profile-type]").textContent=profile?.account_type||"member"}}catch(error){console.error("Auth UI refresh failed:",error)}}
async function handleLogin(form){setFormBusy(form,true,"Signing in…");try{const identifier=form.elements.identifier.value.trim();const password=form.elements.password.value;const credentials=identifier.includes("@")?{email:identifier,password}:{phone:identifier,password};const {error}=await supabaseClient.auth.signInWithPassword(credentials);if(error){authMessage(form,error.message,"error");return}authMessage(form,"Signed in successfully.","success");goToContent("content/home.html")}finally{setFormBusy(form,false)}}
async function handleSignup(form){setFormBusy(form,true,"Creating account…");try{const name=form.elements.name.value.trim();const identifier=form.elements.identifier.value.trim();const password=form.elements.password.value;const confirmPassword=form.elements["confirm-password"].value;if(password.length<8){authMessage(form,"Password must be at least 8 characters.","error");return}if(password!==confirmPassword){authMessage(form,"Passwords do not match.","error");return}const isEmail=identifier.includes("@");const credentials=isEmail?{email:identifier,password}:{phone:identifier,password};const {data,error}=await supabaseClient.auth.signUp({...credentials,options:{data:{name}}});if(error){authMessage(form,error.message,"error");return}if(data.session){authMessage(form,"Account created successfully.","success");goToContent("content/home.html");return}authMessage(form,isEmail?"Account created. Check your email to confirm your account.":"Account created. Check your phone for the verification code.","success")}finally{setFormBusy(form,false)}}
async function handlePasswordResetRequest(form){setFormBusy(form,true,"Sending…");try{const email=form.elements.email.value.trim();const {error}=await supabaseClient.auth.resetPasswordForEmail(email,{redirectTo:getAppBaseUrl()+"#content/forgot-password.html"});if(error){authMessage(form,error.message,"error");return}authMessage(form,"Reset link sent. Check your email.","success")}finally{setFormBusy(form,false)}}
async function handlePasswordUpdate(form){setFormBusy(form,true,"Updating…");try{const session=await getSession();if(!session){authMessage(form,"Open this page from the password reset link.","error");return}const password=form.elements["reset-password"].value;if(password.length<8){authMessage(form,"Password must be at least 8 characters.","error");return}const {error}=await supabaseClient.auth.updateUser({password});if(error){authMessage(form,error.message,"error");return}authMessage(form,"Password updated successfully.","success");setTimeout(()=>goToContent("content/login.html"),700)}finally{setFormBusy(form,false)}}
async function updateRecoveryUI(){const requestForm=document.querySelector('[data-auth-form="password-reset-request"]');const updateForm=document.querySelector('[data-auth-form="password-update"]');const status=document.querySelector("[data-recovery-status]");if(!requestForm||!updateForm)return;const session=await getSession();const recovery=Boolean(session&&sessionStorage.getItem("dalimgari:recovery-mode")==="1");requestForm.hidden=recovery;updateForm.hidden=!recovery;if(status)status.textContent=recovery?"Choose a new password for your account.":"Enter your email to receive a reset link."}
async function handleGoogleLogin(button){button.disabled=true;button.textContent="Connecting…";const {error}=await supabaseClient.auth.signInWithOAuth({provider:"google",options:{redirectTo:getAppBaseUrl()+"#content/home.html"}});if(error){const form=button.closest("form");if(form)authMessage(form,error.message,"error");button.disabled=false;button.textContent="Continue with Google"}}
async function handleLogout(){const {error}=await supabaseClient.auth.signOut();if(error){console.error("Logout failed:",error);return}goToContent("content/home.html")}
document.addEventListener("submit",event=>{const form=event.target;if(form.matches('[data-auth-form="login"]')){event.preventDefault();handleLogin(form).catch(error=>authMessage(form,error.message,"error"))}if(form.matches('[data-auth-form="signup"]')){event.preventDefault();handleSignup(form).catch(error=>authMessage(form,error.message,"error"))}if(form.matches('[data-auth-form="password-reset-request"]')){event.preventDefault();handlePasswordResetRequest(form).catch(error=>authMessage(form,error.message,"error"))}if(form.matches('[data-auth-form="password-update"]')){event.preventDefault();handlePasswordUpdate(form).catch(error=>authMessage(form,error.message,"error"))}});
document.addEventListener("click",event=>{const googleButton=event.target.closest("[data-auth-action='google']");const logoutButton=event.target.closest("[data-auth-action='logout']");if(googleButton){event.preventDefault();handleGoogleLogin(googleButton).catch(error=>console.error("Google login failed:",error))}if(logoutButton){event.preventDefault();handleLogout().catch(error=>console.error("Logout failed:",error))}});
document.addEventListener("dalimgari:page-loaded",()=>{refreshAuthUI();updateRecoveryUI().catch(error=>console.error("Recovery UI update failed:",error))});
supabaseClient.auth.onAuthStateChange((_event,session)=>{if(_event==="PASSWORD_RECOVERY")sessionStorage.setItem("dalimgari:recovery-mode","1");if(_event==="SIGNED_OUT")sessionStorage.removeItem("dalimgari:recovery-mode");updateAuthUI(session);if(["PASSWORD_RECOVERY","SIGNED_IN","SIGNED_OUT"].includes(_event))updateRecoveryUI().catch(error=>console.error("Recovery state update failed:",error))});
window.dalimgariAuth={getSession,loadProfile};refreshAuthUI();