import { useEffect, useState } from 'react'
import { usePreferences } from '../../context/PreferencesContext'
import Header from './Header'
import Sidebar from './Sidebar'
import Footer from './Footer'
import { appPath } from '../../lib/routes'
import { getWebsiteInformation, getRuralVisualSettings } from '../../services/websiteService'
import { getGlobalLabels } from '../../services/globalLabelService'
import { getThemeSettings } from '../../services/themeService'
import { trackPageView } from '../../services/analyticsService'
const ROUTE_TITLES={ '/':'হোম','/information':'গ্রামের তথ্য','/posts':'পোস্ট','/albums':'অ্যালবাম','/search':'খুঁজুন','/login':'লগইন','/signup':'নতুন একাউন্ট','/profile':'প্রোফাইল','/admin':'ড্যাশবোর্ড','/admin/homepage':'হোমপেজ ব্যবস্থাপনা','/admin/sidebar':'সাইডবার ব্যবস্থাপনা','/admin/pages':'পেজ ব্যবস্থাপনা','/admin/posts':'পোস্ট ব্যবস্থাপনা','/admin/albums':'অ্যালবাম ব্যবস্থাপনা','/admin/media':'মিডিয়া ব্যবস্থাপনা','/admin/users':'ব্যবহারকারী ব্যবস্থাপনা','/admin/access':'অ্যাক্সেস ব্যবস্থাপনা','/admin/audit':'অডিট লগ','/admin/analytics':'অ্যানালিটিক্স','/admin/website-information':'ওয়েবসাইট তথ্য','/admin/admin-information':'অ্যাডমিন তথ্য','/admin/rural-visual':'গ্রামীণ ভিজ্যুয়াল ব্যবস্থাপনা' }
function Seo({siteName,title,description,canonicalPath}){useEffect(()=>{const routeKey=canonicalPath||'/';const finalTitle=title||siteName||'';const fullTitle=finalTitle;if(fullTitle)document.title=fullTitle;const setMeta=(selector,attributes,content)=>{let element=document.head.querySelector(selector);if(!content){element?.remove();return}if(!element){element=document.createElement('meta');Object.entries(attributes).forEach(([key,value])=>element.setAttribute(key,value));document.head.appendChild(element)}element.setAttribute('content',content)};setMeta('meta[name="description"]',{name:'description'},description);setMeta('meta[property="og:title"]',{property:'og:title'},fullTitle);setMeta('meta[property="og:description"]',{property:'og:description'},description);let link=document.head.querySelector('link[rel="canonical"]');if(!link){link=document.createElement('link');link.setAttribute('rel','canonical');document.head.appendChild(link)}link.setAttribute('href',new URL(appPath(routeKey),window.location.origin).href)},[siteName,title,description,canonicalPath]);return null}

function applyThemeSettings(settings, theme) {
  const root = document.documentElement
  const palette = settings?.[theme] || {}
  const wallpaper = palette.wallpaper || ''
  if (wallpaper) root.style.setProperty('--rural-wallpaper', `url("${wallpaper}")`)
  const icons = palette.icons || {}
  if (icons.color) root.style.setProperty('--theme-icon-color', String(icons.color))
  if (icons.size) root.style.setProperty('--theme-icon-size', String(icons.size))
  if (icons.strokeWidth) root.style.setProperty('--theme-icon-stroke-width', String(icons.strokeWidth))
  if (icons.opacity) root.style.setProperty('--theme-icon-opacity', String(icons.opacity))
  if (icons.shadow) root.style.setProperty('--theme-icon-shadow', String(icons.shadow))
  const colors = palette.colors || {}
  const states = palette.states || {}
  const interaction = palette.interaction || {}
  const shape = palette.shape || {}
  const shadow = palette.shadow || {}
  const typography = palette.typography || {}
  const scrollbar = palette.scrollbar || {}
  const vars = {earth: colors.earth, earthDark: colors.earthDark, leaf: colors.leaf, leafDark: colors.leafDark,paddy: colors.paddy, field: colors.field, water: colors.water, clay: colors.clay, sun: colors.sun,page: colors.page, surface: colors.surface, surfaceSoft: colors.surfaceSoft, text: colors.text,muted: colors.muted, border: colors.border, focus: colors.focus, shadow: colors.shadow,header: colors.header, footer: colors.footer, input: colors.input, hover: colors.hover,success: states.success, warning: states.warning, error: states.error, info: states.info,hoverOpacity: interaction.hoverOpacity, activeOpacity: interaction.activeOpacity, disabledOpacity: interaction.disabledOpacity,radius: shape.radius, buttonRadius: shape.buttonRadius, borderWidth: shape.borderWidth,shadowCard: shadow.card, shadowDropdown: shadow.dropdown, shadowModal: shadow.modal,headingWeight: typography.headingWeight, bodyWeight: typography.bodyWeight, lineHeight: typography.lineHeight,scrollbarThumb: scrollbar.thumb, scrollbarTrack: scrollbar.track}
  Object.entries(vars).forEach(([key, value]) => { if (value !== undefined && value !== null && value !== '') root.style.setProperty(`--theme-${key}`, String(value)) })
}

function applyRuralVisualSettings(settings){if(!settings)return;const root=document.documentElement;if(settings.wallpaper_position)root.style.setProperty('--rural-wallpaper-position',settings.wallpaper_position);if(settings.wallpaper_size)root.style.setProperty('--rural-wallpaper-size',settings.wallpaper_size);const text=settings.text_styles||{};if(text.heading_font)root.style.setProperty('--rural-heading-font',`'${text.heading_font}', 'Noto Serif Bengali', Georgia, serif`);if(text.body_font)root.style.setProperty('--rural-body-font',`'${text.body_font}', 'Noto Sans Bengali', sans-serif`);if(text.heading_weight)root.style.setProperty('--rural-heading-weight',String(text.heading_weight));const component=settings.component_styles||{};if(component.radius)root.style.setProperty('--rural-radius',component.radius)}

export default function Layout({children,siteName,slogan,navigationItems=[],copyrightText,seoTitle,seoDescription,seoCanonicalPath,sidebarConfig}){const {theme,language,deviceClass}=usePreferences();const [websiteInformation,setWebsiteInformation]=useState(null);const [visualSettings,setVisualSettings]=useState(null);const [sidebarOpen,setSidebarOpen]=useState(false);const [labels,setLabels]=useState({});const [themeSettings,setThemeSettings]=useState(null);useEffect(()=>{let active=true;Promise.allSettled([getWebsiteInformation(),getRuralVisualSettings(),getGlobalLabels(),getThemeSettings() ]).then(([info,visual,labelResult,themeResult])=>{if(!active)return;if(info.status==='fulfilled')setWebsiteInformation(info.value);if(visual.status==='fulfilled'){setVisualSettings(visual.value);applyRuralVisualSettings(visual.value)}if(labelResult.status==='fulfilled')setLabels(labelResult.value);if(themeResult?.status==='fulfilled'){setThemeSettings(themeResult.value);applyThemeSettings(themeResult.value,theme)}});return()=>{active=false}},[]);useEffect(()=>{if(visualSettings)applyRuralVisualSettings(visualSettings);if(themeSettings)applyThemeSettings(themeSettings,theme)},[visualSettings,themeSettings,theme]);const resolvedSiteName=siteName??websiteInformation?.village_name;const resolvedSlogan=slogan??websiteInformation?.slogan;const resolvedCopyright=copyrightText??websiteInformation?.copyright_text;const canonicalPath=seoCanonicalPath||(()=>{const base=import.meta.env.BASE_URL||'/';const pathname=window.location.pathname;if(base!=='/'&&pathname.startsWith(base))return pathname.slice(base.length-1)||'/';return pathname||'/'})();useEffect(()=>{trackPageView({path:canonicalPath,deviceClass,language,theme}).catch(()=>{})},[canonicalPath,deviceClass,language,theme]);return <div className="site-layout"><a className="skip-link" href="#main-content">মূল জায়গায় যান</a><Seo siteName={resolvedSiteName} title={seoTitle||ROUTE_TITLES[canonicalPath]||null} description={seoDescription} canonicalPath={canonicalPath}/><Header pageTitle={seoTitle||ROUTE_TITLES[canonicalPath]||'হোম'} labels={labels} sidebarOpen={sidebarOpen} showSearch={canonicalPath==='/' } canonicalPath={canonicalPath} onMenu={()=>setSidebarOpen(v=>!v)}/><div className={`site-body${sidebarOpen?' sidebar-visible':''}`}><Sidebar items={navigationItems} open={sidebarOpen} onClose={()=>setSidebarOpen(false)} labels={labels} canonicalPath={canonicalPath}/><main id="main-content" className="site-main">{children}</main></div><Footer copyrightText={resolvedCopyright}/></div>}