import { useEffect, useState } from 'react'
import Header from './Header'
import Sidebar from './Sidebar'
import Footer from './Footer'
import { appPath } from '../../lib/routes'
import { getWebsiteInformation } from '../../services/websiteService'
const ROUTE_TITLES={ '/':'হোম','/information':'গ্রামের তথ্য','/posts':'পোস্ট','/albums':'অ্যালবাম','/search':'সার্চ','/login':'লগইন','/profile':'প্রোফাইল' }
function Seo({siteName,title,description,canonicalPath}){useEffect(()=>{const routeKey=canonicalPath||'/';const finalTitle=title||siteName||'';const fullTitle=finalTitle&&siteName&&finalTitle!==siteName?`${finalTitle} | ${siteName}`:finalTitle;if(fullTitle)document.title=fullTitle;const setMeta=(selector,attributes,content)=>{let element=document.head.querySelector(selector);if(!content){element?.remove();return}if(!element){element=document.createElement('meta');Object.entries(attributes).forEach(([key,value])=>element.setAttribute(key,value));document.head.appendChild(element)}element.setAttribute('content',content)};setMeta('meta[name="description"]',{name:'description'},description);setMeta('meta[property="og:title"]',{property:'og:title'},fullTitle);setMeta('meta[property="og:description"]',{property:'og:description'},description);let link=document.head.querySelector('link[rel="canonical"]');if(!link){link=document.createElement('link');link.setAttribute('rel','canonical');document.head.appendChild(link)}link.setAttribute('href',new URL(appPath(routeKey),window.location.origin).href)},[siteName,title,description,canonicalPath]);return null}
export default function Layout({children,siteName,slogan,navigationItems=[],copyrightText,seoTitle,seoDescription,seoCanonicalPath}){const [websiteInformation,setWebsiteInformation]=useState(null);const [sidebarOpen,setSidebarOpen]=useState(false);useEffect(()=>{let active=true;getWebsiteInformation().then(data=>{if(active)setWebsiteInformation(data)}).catch(()=>{if(active)setWebsiteInformation(null)});return()=>{active=false}},[]);const resolvedSiteName=siteName??websiteInformation?.village_name;const resolvedSlogan=slogan??websiteInformation?.slogan;const resolvedCopyright=copyrightText??websiteInformation?.copyright_text;const canonicalPath=seoCanonicalPath||(()=>{const base=import.meta.env.BASE_URL||'/';const pathname=window.location.pathname;if(base!=='/'&&pathname.startsWith(base))return pathname.slice(base.length-1)||'/';return pathname||'/'})();return <div className="site-layout"><a className="skip-link" href="#main-content">মূল কনটেন্টে যান</a><Seo siteName={resolvedSiteName} title={seoTitle||ROUTE_TITLES[canonicalPath]||null} description={seoDescription} canonicalPath={canonicalPath}/><Header siteName={resolvedSiteName} slogan={resolvedSlogan} onMenu={()=>setSidebarOpen(true)}/><Sidebar items={navigationItems} open={sidebarOpen} onClose={()=>setSidebarOpen(false)}/><main id="main-content" className="site-main">{children}</main><Footer copyrightText={resolvedCopyright}/></div>}
