import {toggleSave,sharePost,reactToPost,getComments,addComment,addReply,getPostState,updatePost,deletePost} from "../../services/posts.js";
const esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const authorName=u=>u?.display_name||u?.user_metadata?.full_name||u?.user_metadata?.name||u?.email?.split("@")[0]||"Community member";
function avatar(u){return u?.avatar_url||u?.user_metadata?.avatar_url||u?.user_metadata?.picture||"./component/avatar/default-avatar-day.svg"}
function mediaMarkup(items=[]){if(!items.length)return "";return '<div class="post-card__media">'+items.sort((a,b)=>(a.sort_order||0)-(b.sort_order||0)).map(x=>{const m=x.Media;if(!m?.media_url)return "";return m.media_type==="video"?'<video controls preload="metadata" src="'+esc(m.media_url)+'"></video>':'<img loading="lazy" src="'+esc(m.thumbnail_url||m.media_url)+'" alt="'+esc(m.title||"Post media")+'">'}).join("")+"</div>"}
function counts(post){return {likes:(post.post_reactions||[]).length,comments:(post.comments||[]).length,shares:(post.post_shares||[]).length}}
export async function renderPostCard(post){
 const el=document.createElement("article");el.className="post-card card";el.dataset.postId=post.id;
 const state=await getPostState(post.id),c=counts(post),author=post.User,ctx=await window.dalimgariAccess?.getContext?.(),isOwner=ctx?.user?.id===post.user_id;
 el.innerHTML='<header class="post-card__head"><a href="#content/profile.html" data-route="content/profile.html" class="post-card__author"><img class="post-card__avatar" src="'+esc(avatar(author))+'" alt=""><span><strong>'+esc(authorName(author))+'</strong><small>'+new Date(post.created_at).toLocaleString()+(post.updated_at&&post.updated_at!==post.created_at?" · edited":"")+'</small></span></a>'+(isOwner?'<div class="post-card__manage"><button type="button" data-post-edit>Edit</button><button type="button" data-post-delete>Delete</button></div>':"")+'</header><div class="post-card__body" data-post-content>'+esc(post.content)+'</div>'+mediaMarkup(post.post_media)+'<div class="post-card__summary"><span data-like-count>'+c.likes+' reactions</span><span data-comment-count>'+c.comments+' comments</span><span data-share-count>'+c.shares+' shares</span></div><footer class="post-card__actions"><button type="button" data-post-action="react">'+(state.reaction?"Liked":"Like")+'</button><button type="button" data-post-action="comment">Comment</button><button type="button" data-post-action="share">Share</button><button type="button" data-post-action="save">'+(state.saved?"Saved":"Save")+'</button></footer><section class="post-card__comments" data-comments-panel hidden><div data-comments-list></div><form data-comment-form><input name="content" maxlength="2000" placeholder="Write a comment…" required><button class="button button--secondary" type="submit">Comment</button></form></section>';
 const commentsPanel=el.querySelector("[data-comments-panel]");
 const loadComments=async()=>{const box=el.querySelector("[data-comments-list]"),r=await getComments(post.id);if(r.error){box.textContent=r.error.message;return}box.innerHTML=(r.data||[]).map(c=>'<div class="post-comment" data-comment-id="'+c.id+'"><strong>'+esc(authorName(c.User))+'</strong><p>'+esc(c.content)+'</p><button type="button" data-reply>Reply</button><div class="post-replies">'+(c.post_replies||[]).map(x=>'<div class="post-reply"><strong>'+esc(authorName(x.User))+'</strong><span>'+esc(x.content)+'</span></div>').join("")+'<form data-reply-form hidden><input name="content" maxlength="2000" placeholder="Write a reply…" required><button class="button button--secondary">Reply</button></form></div></div>').join("")||'<div class="empty">No comments yet.</div>'};
 el.querySelector('[data-post-action="react"]').addEventListener("click",async e=>{const r=await reactToPost(post.id,"like");if(r.error)return;state.reaction=state.reaction?"": "like";e.currentTarget.textContent=state.reaction?"Liked":"Like";c.likes=Math.max(0,c.likes+(state.reaction?1:-1));el.querySelector("[data-like-count]").textContent=c.likes+" reactions"});
 el.querySelector('[data-post-action="comment"]').addEventListener("click",async()=>{commentsPanel.hidden=!commentsPanel.hidden;if(!commentsPanel.hidden)await loadComments()});
 el.querySelector('[data-post-action="share"]').addEventListener("click",async e=>{const r=await sharePost(post.id);if(!r.error&&r.created){c.shares++;el.querySelector("[data-share-count]").textContent=c.shares+" shares";e.currentTarget.textContent="Shared"}});
 el.querySelector('[data-post-action="save"]').addEventListener("click",async e=>{const r=await toggleSave(post.id,state.saved);if(!r.error){state.saved=!state.saved;e.currentTarget.textContent=state.saved?"Saved":"Save"}});
 el.querySelector("[data-comment-form]").addEventListener("submit",async e=>{e.preventDefault();const input=e.currentTarget.elements.content,r=await addComment(post.id,input.value);if(!r.error){input.value="";c.comments++;el.querySelector("[data-comment-count]").textContent=c.comments+" comments";await loadComments()}});
 el.querySelector("[data-comments-list]").addEventListener("click",e=>{const b=e.target.closest("[data-reply]");if(!b)return;b.nextElementSibling?.querySelector("form")?.removeAttribute("hidden")});
 el.querySelector("[data-comments-list]").addEventListener("submit",async e=>{if(!e.target.matches("[data-reply-form]"))return;e.preventDefault();const box=e.target.closest("[data-comment-id]"),r=await addReply(box.dataset.commentId,e.target.elements.content.value);if(!r.error)await loadComments()});
 el.querySelector("[data-post-edit]")?.addEventListener("click",async()=>{const next=prompt("Edit post",post.content);if(next===null)return;const r=await updatePost(post.id,{content:next,visibility:post.visibility});if(!r.error){post.content=r.data.content;el.querySelector("[data-post-content]").textContent=r.data.content}});
 el.querySelector("[data-post-delete]")?.addEventListener("click",async()=>{if(!confirm("Delete this post?"))return;const r=await deletePost(post.id);if(!r.error)el.remove()});
 return el;
}