function authError(message,cause=null){return{error:{message,cause}};}
function normalizeError(error){if(!error)return null;const message=error.message||"Authentication request failed.";const map={"Invalid login credentials":"Invalid email / phone or password.","Email not confirmed":"Please confirm your email before signing in.","User already registered":"An account with this email already exists.","Password should be at least 6 characters.":"Password must be at least 6 characters."};return{message:map[message]||message};}
function getClient(){return window.Dalimgari?.supabase||null;}
async function login(identifier,password){const client=getClient();if(!client)return authError("Authentication service is unavailable.");if(!identifier||!password)return authError("Email / phone and password are required.");const credentials=identifier.includes("@")?{email:identifier.trim(),password}:{phone:identifier.trim(),password};const response=await client.auth.signInWithPassword(credentials);return response?.error?{...response,error:normalizeError(response.error)}:response;}
async function register(email,password){const client=getClient();if(!client)return authError("Authentication service is unavailable.");if(!email||!password)return authError("Email and password are required.");const response=await client.auth.signUp({email:email.trim(),password});return response?.error?{...response,error:normalizeError(response.error)}:response;}
function getPasswordResetRedirect(){return window.Dalimgari?.config?.passwordResetRedirect||window.location.origin;}
async function resetPassword(email){const client=getClient();if(!client)return authError("Authentication service is unavailable.");if(!email)return authError("Email is required.");const response=await client.auth.resetPasswordForEmail(email.trim(),{redirectTo:getPasswordResetRedirect()});return response?.error?{...response,error:normalizeError(response.error)}:response;}
async function updatePassword(password){const client=getClient();if(!client)return authError("Authentication service is unavailable.");if(!password)return authError("New password is required.");const response=await client.auth.updateUser({password});return response?.error?{...response,error:normalizeError(response.error)}:response;}
async function getSession(){const client=getClient();if(!client)return authError("Authentication service is unavailable.");const response=await client.auth.getSession();return response?.error?{...response,error:normalizeError(response.error)}:response;}
async function logout(){const client=getClient();if(!client)return authError("Authentication service is unavailable.");const response=await client.auth.signOut();return response?.error?{...response,error:normalizeError(response.error)}:response;}
async function initializeAuth(){const client=getClient();if(!client){window.Dalimgari.controller?.dispatch("auth-state-change",{session:null,error:{message:"Authentication service is unavailable."}});return;}client.auth.onAuthStateChange((event,session)=>{window.Dalimgari.controller?.dispatch("auth-state-change",{event,session});});const response=await getSession();if(response?.error){window.Dalimgari.controller?.dispatch("auth-state-change",{session:null,error:response.error});return;}window.Dalimgari.controller?.dispatch("auth-state-change",{event:"INITIAL_SESSION",session:response.data.session});}
window.Dalimgari=window.Dalimgari||{};window.Dalimgari.auth={login,register,resetPassword,updatePassword,logout,getSession,initialize:initializeAuth};