// Media and post content management
(function(){
const client=()=>window.Dalimgari?.supabase||null, fail=(message,cause=null)=>({error:{message,cause}});
const profile=async()=>{const c=client();if(!c)return fail("Database service is unavailable.");const{data:u,error:ue}=await c.auth.getUser();if(ue||!u?.user)return fail("You must be signed in.");const{data,error}=await c.from("profiles").select("id,is_admin,is_active").eq("id",u.user.id).single();return error?fail(error.message,error):(!data.is_active?fail("This account is disabled."):{data});};
const visibility=v=>["public","members","private"].includes(v)?v:"public";
const listAlbums=async()=>{const{data,error}=await client().from("albums").select("id,title,description,created_by,created_at,updated_at").order("created_at",{ascending:false});return error?fail(error.message,error):{data:data||[]};};
const createAlbum=async(title,description="")=>{const me=await profile();if(me.error||!me.data.is_admin)return fail("Admin access required.");title=String(title||"").trim();if(!title)return fail("Album title is required.");const{data,error}=await client().from("albums").insert({title,description:String(description||"").trim()||null,created_by:me.data.id}).select().single();return error?fail(error.message,error):{data};};
const deleteAlbum=async id=>{const me=await profile();if(me.error||!me.data.is_admin)return fail("Admin access required.");const{error}=await client().from("albums").delete().eq("id",id);return error?fail(error.message,error):{data:true};};
const upload=async(uid,pid,type,file)=>{if(!file)return null;const max=type==="photo"?20*1024*1024:100*1024*1024;if(file.size>max)return fail(type==="photo"?"Photo must be 20 MB or smaller.":"Video must be 100 MB or smaller.");const safe=String(file.name||"file").replace(/[^a-zA-Z0-9._-]+/g,"-").slice(-120)||"file";const path=uid+"/"+pid+"/"+type+"-"+Date.now()+"-"+safe;const{error}=await client().storage.from("media").upload(path,file,{cacheControl:"3600",upsert:false,contentType:file.type||undefined});return error?fail(error.message,error):{path};};
const createPost=async(p={})=>{const me=await profile();if(me.error)return me;const caption=String(p.caption??p.content??"").trim();if(!caption)return fail("Caption is required.");if(caption.length>5000)return fail("Caption must be 5000 characters or fewer.");const albumId=p.albumId||null;if(albumId){const{data:album,error}=await client().from("albums").select("id").eq("id",albumId).maybeSingle();if(error)return fail(error.message,error);if(!album)return fail("Selected album was not found.");}const{data:post,error}=await client().from("posts").insert({user_id:me.data.id,content:caption,description:String(p.description||"").trim()||null,visibility:visibility(p.visibility),album_id:albumId}).select("id,user_id,content,description,visibility,album_id,created_at,updated_at").single();if(error)return fail(error.message,error);const uploaded=[];try{for(const[type,file]of[["photo",p.photo],["video",p.video]])if(file){const u=await upload(me.data.id,post.id,type,file);if(u?.error)throw u;uploaded.push({type,file,path:u.path});}if(uploaded.length){const{error:e}=await client().from("media").insert(uploaded.map(x=>({post_id:post.id,album_id:albumId,type:x.type,storage_path:x.path,original_name:x.file.name||null,mime_type:x.file.type||null,size_bytes:x.file.size,created_by:me.data.id})));if(e)throw fail(e.message,e);}return{data:post};}catch(e){if(uploaded.length)await client().storage.from("media").remove(uploaded.map(x=>x.path));await client().from("posts").delete().eq("id",post.id);return e?.error?e:fail(e?.message||"Unable to publish post.",e);}};
const listPosts=async(filter="all")=>{const{data,error}=await client().from("posts").select("id,user_id,content,description,visibility,album_id,created_at,updated_at,profiles(display_name,email,avatar_url),albums(id,title),media(id,type,storage_path,original_name,mime_type,size_bytes)").order("created_at",{ascending:false}).limit(100);if(error)return fail(error.message,error);let rows=data||[];if(filter==="photos")rows=rows.filter(p=>(p.media||[]).some(m=>m.type==="photo"));if(filter==="videos")rows=rows.filter(p=>(p.media||[]).some(m=>m.type==="video"));return{data:rows};};
const listMedia=async(type="all")=>{const{data,error}=await client().from("media").select("id,post_id,album_id,type,storage_path,original_name,mime_type,size_bytes,created_at,posts(id,content,description,visibility),albums(id,title),profiles:created_by(display_name,email)").order("created_at",{ascending:false}).limit(200);if(error)return fail(error.message,error);return{data:type==="all"?data||[]:(data||[]).filter(x=>x.type===type)};};
const deletePost=async id=>{const me=await profile();if(me.error||!me.data.is_admin)return fail("Admin access required.");const{data:items,error}=await client().from("media").select("storage_path").eq("post_id",id);if(error)return fail(error.message,error);const paths=(items||[]).map(x=>x.storage_path).filter(Boolean);if(paths.length){const{error:e}=await client().storage.from("media").remove(paths);if(e)return fail(e.message,e);}const{error:e}=await client().from("posts").delete().eq("id",id);return e?fail(e.message,e):{data:true};};
const updatePost=async(id,p={})=>{const me=await profile();if(me.error||!me.data.is_admin)return fail("Admin access required.");const caption=String(p.caption||"").trim();if(!caption)return fail("Caption is required.");const{error}=await client().from("posts").update({content:caption,description:String(p.description||"").trim()||null,visibility:visibility(p.visibility),album_id:p.albumId||null,updated_at:new Date().toISOString()}).eq("id",id);return error?fail(error.message,error):{data:true};};
const signedUrl=async path=>{const{data,error}=await client().storage.from("media").createSignedUrl(path,3600);return error?null:data?.signedUrl||null;};
window.Dalimgari=window.Dalimgari||{};window.Dalimgari.media={listAlbums,createAlbum,deleteAlbum,createPost,listPosts,listMedia,deletePost,updatePost,signedUrl};
})();