import {getNotifications,getUnreadCount,markNotificationRead,markAllNotificationsRead} from "../../services/notifications.js";
const esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const labels={reaction:"reacted to your post",comment:"commented on your post",reply:"replied to your comment",share:"shared your post",follow:"started following you",friend_request:"sent you a friend request",friend_accept:"accepted your friend request",message:"sent you a message"};
export async function initNotifications(root=document){
 const center=root.querySelector("[data-notification-center]");if(!center)return;
 const panel=center.querySelector("[data-notification-panel]"),list=center.querySelector("[data-notification-list]"),badge=center.querySelector("[data-notification-badge]");
 const refresh=async()=>{const [r,count]=await Promise.all([getNotifications(),getUnreadCount()]);badge.hidden=!count;badge.textContent=count;if(r.error)return;list.innerHTML=(r.data||[]).map(n=>{const name=n.User?.display_name||"Someone";const target=n.type==="message"?"#content/messenger.html?user="+encodeURIComponent(n.actor_id||""):n.entity_type==="post"&&n.entity_id?"#content/home.html":"#content/profile.html?user="+encodeURIComponent(n.actor_id||"");return '<a class="notification-item '+(!n.read_at?"is-unread":"")+'" href="'+target+'" data-notification-id="'+esc(n.id)+'" data-entity-type="'+esc(n.entity_type||"")+'" data-entity-id="'+esc(n.entity_id||"")+'"><strong>'+esc(name)+" "+esc(labels[n.type]||"sent you a notification")+'</strong><small>'+new Date(n.created_at).toLocaleString()+'</small></a>'}).join("")||'<div class="empty">No notifications.</div>'};
 center.querySelector("[data-notification-toggle]").addEventListener("click",async()=>{const open=panel.hidden;panel.hidden=!open;center.querySelector("[data-notification-toggle]").setAttribute("aria-expanded",String(open));if(open)await refresh()});
 center.querySelector("[data-notification-read-all]").addEventListener("click",async()=>{await markAllNotificationsRead();await refresh()});
 list.addEventListener("click",async e=>{const item=e.target.closest("[data-notification-id]");if(!item)return;await markNotificationRead(item.dataset.notificationId);if(item.dataset.entityType==="post"&&item.dataset.entityId){sessionStorage.setItem("dalimgari:focusPost",item.dataset.entityId)}});
 await refresh();
 setInterval(refresh,30000);
}