-- Community platform core schema.
create table if not exists public.posts (id uuid primary key default gen_random_uuid(), user_id uuid not null references public."User"(user_id) on delete cascade, content text not null check (length(trim(content)) between 1 and 5000), visibility text not null default 'public' check (visibility in ('public','members')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.comments (id uuid primary key default gen_random_uuid(), post_id uuid not null references public.posts(id) on delete cascade, user_id uuid not null references public."User"(user_id) on delete cascade, content text not null check (length(trim(content)) between 1 and 2000), created_at timestamptz not null default now());
create table if not exists public.post_reactions (post_id uuid not null references public.posts(id) on delete cascade, user_id uuid not null references public."User"(user_id) on delete cascade, reaction text not null default 'like' check (reaction in ('like','love','support')), created_at timestamptz not null default now(), primary key(post_id,user_id));
create table if not exists public.announcements (id uuid primary key default gen_random_uuid(), author_id uuid references public."User"(user_id) on delete set null, title text not null check(length(trim(title)) between 1 and 180), content text not null check(length(trim(content)) between 1 and 5000), published boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.events (id uuid primary key default gen_random_uuid(), creator_id uuid references public."User"(user_id) on delete set null, title text not null check(length(trim(title)) between 1 and 180), description text, location text, starts_at timestamptz not null, ends_at timestamptz, created_at timestamptz not null default now());
create table if not exists public.event_rsvps (event_id uuid not null references public.events(id) on delete cascade, user_id uuid not null references public."User"(user_id) on delete cascade, status text not null default 'going' check(status in ('going','interested','not_going')), created_at timestamptz not null default now(), primary key(event_id,user_id));
create table if not exists public.reports (id uuid primary key default gen_random_uuid(), reporter_id uuid not null references public."User"(user_id) on delete cascade, post_id uuid references public.posts(id) on delete cascade, comment_id uuid references public.comments(id) on delete cascade, reason text not null check(length(trim(reason)) between 1 and 1000), status text not null default 'open' check(status in ('open','reviewing','resolved','dismissed')), created_at timestamptz not null default now(), resolved_at timestamptz);
create index if not exists posts_created_idx on public.posts(created_at desc); create index if not exists comments_post_idx on public.comments(post_id,created_at); create index if not exists reactions_post_idx on public.post_reactions(post_id); create index if not exists events_start_idx on public.events(starts_at);
alter table public.posts enable row level security; alter table public.comments enable row level security; alter table public.post_reactions enable row level security; alter table public.announcements enable row level security; alter table public.events enable row level security; alter table public.event_rsvps enable row level security; alter table public.reports enable row level security;
create or replace function public.touch_community_updated_at() returns trigger language plpgsql set search_path='' as $$ begin new.updated_at=now(); return new; end; $$;
drop trigger if exists posts_touch on public.posts; create trigger posts_touch before update on public.posts for each row execute function public.touch_community_updated_at();
drop trigger if exists announcements_touch on public.announcements; create trigger announcements_touch before update on public.announcements for each row execute function public.touch_community_updated_at();
