-- Social platform completion batch: Stories, Groups, Pages, Saved Collections and block enforcement.
create table if not exists public.stories (id uuid primary key default gen_random_uuid(), user_id uuid not null references public."User"(user_id) on delete cascade, media_url text not null, media_type text not null check(media_type in ('image','video')), caption text, created_at timestamptz not null default now(), expires_at timestamptz not null default (now()+interval '24 hours'));
create table if not exists public.groups (id uuid primary key default gen_random_uuid(), owner_id uuid references public."User"(user_id) on delete set null, name text not null, description text, visibility text not null default 'public' check(visibility in ('public','private')), created_at timestamptz not null default now());
create table if not exists public.group_members (group_id uuid not null references public.groups(id) on delete cascade,user_id uuid not null references public."User"(user_id) on delete cascade,role text not null default 'member',status text not null default 'active',created_at timestamptz not null default now(),primary key(group_id,user_id));
create table if not exists public.pages (id uuid primary key default gen_random_uuid(),owner_id uuid references public."User"(user_id) on delete set null,name text not null,description text,avatar_url text,created_at timestamptz not null default now());
create table if not exists public.page_followers (page_id uuid not null references public.pages(id) on delete cascade,user_id uuid not null references public."User"(user_id) on delete cascade,created_at timestamptz not null default now(),primary key(page_id,user_id));
create table if not exists public.saved_collections (id uuid primary key default gen_random_uuid(),user_id uuid not null references public."User"(user_id) on delete cascade,name text not null,created_at timestamptz not null default now());
create table if not exists public.saved_post_collection_items (collection_id uuid not null references public.saved_collections(id) on delete cascade,post_id uuid not null,user_id uuid not null references public."User"(user_id) on delete cascade,created_at timestamptz not null default now(),primary key(collection_id,post_id),foreign key(post_id,user_id) references public.saved_posts(post_id,user_id) on delete cascade);
alter table public.stories enable row level security; alter table public.groups enable row level security; alter table public.group_members enable row level security; alter table public.pages enable row level security; alter table public.page_followers enable row level security; alter table public.saved_collections enable row level security; alter table public.saved_post_collection_items enable row level security;
-- Runtime policies are maintained by the applied Supabase migrations for this batch.
-- Messaging and post visibility are additionally filtered by block relationships.
