create table if not exists public.user_permissions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  permission text not null,
  created_at timestamptz not null default now(),
  unique (user_id, permission)
);

alter table public.user_permissions enable row level security;

create policy "Users can view own permissions"
on public.user_permissions
for select
to authenticated
using (auth.uid() = user_id);

create policy "Admins can manage user permissions"
on public.user_permissions
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Authenticated users can upload media" on storage.objects;
drop policy if exists "Authenticated users can update media" on storage.objects;
drop policy if exists "Authenticated users can delete media" on storage.objects;

create policy "Admins and permitted users can upload media"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'media'
  and (
    public.is_admin()
    or exists (
      select 1
      from public.user_permissions
      where user_id = auth.uid()
      and permission = 'media_upload'
    )
  )
);

create policy "Admins and permitted users can update media"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'media'
  and (
    public.is_admin()
    or exists (
      select 1
      from public.user_permissions
      where user_id = auth.uid()
      and permission = 'media_upload'
    )
  )
)
with check (
  bucket_id = 'media'
  and (
    public.is_admin()
    or exists (
      select 1
      from public.user_permissions
      where user_id = auth.uid()
      and permission = 'media_upload'
    )
  )
);

create policy "Admins and permitted users can delete media"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'media'
  and (
    public.is_admin()
    or exists (
      select 1
      from public.user_permissions
      where user_id = auth.uid()
      and permission = 'media_delete'
    )
  )
);

create index if not exists user_permissions_user_id_idx
on public.user_permissions(user_id);

create index if not exists user_permissions_permission_idx
on public.user_permissions(permission);
