-- Media and post content management
alter table public.posts add column if not exists description text, add column if not exists visibility text not null default 'public', add column if not exists album_id uuid;
alter table public.posts drop constraint if exists posts_visibility_check;
alter table public.posts add constraint posts_visibility_check check (visibility in ('public','members','private'));
create table if not exists public.albums (id uuid primary key default gen_random_uuid(),title text not null check(length(btrim(title)) between 1 and 160),description text,created_by uuid not null references public.profiles(id) on delete cascade,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.media (id uuid primary key default gen_random_uuid(),post_id uuid not null references public.posts(id) on delete cascade,album_id uuid references public.albums(id) on delete set null,type text not null check(type in ('photo','video')),storage_path text not null unique,original_name text,mime_type text,size_bytes bigint,created_by uuid not null references public.profiles(id) on delete cascade,created_at timestamptz not null default now());
alter table public.posts drop constraint if exists posts_album_id_fkey;
alter table public.posts add constraint posts_album_id_fkey foreign key(album_id) references public.albums(id) on delete set null;
create unique index if not exists media_one_photo_per_post_idx on public.media(post_id) where type='photo';
create unique index if not exists media_one_video_per_post_idx on public.media(post_id) where type='video';
create index if not exists media_post_id_idx on public.media(post_id);
create index if not exists media_album_id_idx on public.media(album_id);
create index if not exists media_created_by_idx on public.media(created_by);
create index if not exists albums_created_by_idx on public.albums(created_by);
alter table public.albums enable row level security; alter table public.media enable row level security;
grant select on public.albums,public.media to anon,authenticated; grant insert,update,delete on public.albums,public.media to authenticated; grant select,insert,update,delete on public.posts to authenticated; grant select on public.posts to anon;
drop policy if exists posts_select on public.posts; drop policy if exists posts_select_authenticated on public.posts; drop policy if exists posts_select_public on public.posts;
create policy posts_select_public on public.posts for select to anon using(visibility='public');
create policy posts_select_authenticated on public.posts for select to authenticated using(visibility in('public','members') or (select private.is_admin()) or (select auth.uid())=user_id);
drop policy if exists albums_select on public.albums; create policy albums_select on public.albums for select to anon,authenticated using(true);
drop policy if exists albums_admin_insert on public.albums; create policy albums_admin_insert on public.albums for insert to authenticated with check((select private.is_admin()) and (select auth.uid())=created_by);
drop policy if exists albums_admin_update on public.albums; create policy albums_admin_update on public.albums for update to authenticated using((select private.is_admin())) with check((select private.is_admin()));
drop policy if exists albums_admin_delete on public.albums; create policy albums_admin_delete on public.albums for delete to authenticated using((select private.is_admin()));
drop policy if exists media_select on public.media; create policy media_select on public.media for select to anon,authenticated using(exists(select 1 from public.posts p where p.id=media.post_id and (p.visibility='public' or ((select auth.uid()) is not null and p.visibility='members') or (select private.is_admin()) or (select auth.uid())=p.user_id)));
drop policy if exists media_insert on public.media; create policy media_insert on public.media for insert to authenticated with check((select private.is_admin()) or ((select auth.uid())=created_by and exists(select 1 from public.posts p where p.id=post_id and p.user_id=(select auth.uid()))));
drop policy if exists media_update on public.media; create policy media_update on public.media for update to authenticated using((select private.is_admin()) or (select auth.uid())=created_by) with check((select private.is_admin()) or (select auth.uid())=created_by);
drop policy if exists media_delete on public.media; create policy media_delete on public.media for delete to authenticated using((select private.is_admin()) or (select auth.uid())=created_by);
insert into storage.buckets(id,name,public) values('media','media',false) on conflict(id) do update set public=false;
drop policy if exists media_storage_insert on storage.objects; create policy media_storage_insert on storage.objects for insert to authenticated with check(bucket_id='media' and (storage.foldername(name))[1]=(select auth.uid())::text);
drop policy if exists media_storage_select on storage.objects; create policy media_storage_select on storage.objects for select to anon,authenticated using(bucket_id='media' and exists(select 1 from public.media m join public.posts p on p.id=m.post_id where m.storage_path=name and (p.visibility='public' or ((select auth.uid()) is not null and p.visibility='members') or (select private.is_admin()) or (select auth.uid())=p.user_id)));
drop policy if exists media_storage_delete on storage.objects; create policy media_storage_delete on storage.objects for delete to authenticated using(bucket_id='media' and ((select private.is_admin()) or exists(select 1 from public.media m where m.storage_path=name and m.created_by=(select auth.uid()))));
drop policy if exists media_storage_update on storage.objects; create policy media_storage_update on storage.objects for update to authenticated using(bucket_id='media' and ((select private.is_admin()) or exists(select 1 from public.media m where m.storage_path=name and m.created_by=(select auth.uid())))) with check(bucket_id='media');
