alter table public.theme_settings add column if not exists theme_key text;
alter table public.theme_settings drop constraint if exists theme_settings_active_visual_theme_check;
update public.theme_settings set theme_key='nature', settings_key='theme_nature', active_visual_theme='nature', is_active=false where settings_key='global';
create unique index if not exists theme_settings_theme_key_uidx on public.theme_settings(theme_key) where theme_key is not null;
alter table public.theme_settings add constraint theme_settings_theme_key_check check (theme_key in ('classic','glass','nature'));
alter table public.theme_settings add constraint theme_settings_active_visual_theme_check check (active_visual_theme in ('classic','glass','nature'));
drop policy if exists theme_settings_public_read on public.theme_settings;
create policy theme_settings_public_read on public.theme_settings for select to anon, authenticated using (is_active=true);
drop policy if exists theme_settings_admin_select on public.theme_settings;
create policy theme_settings_admin_select on public.theme_settings for select to authenticated using ((select private.has_permission('settings_manage'::text)));

insert into public.theme_settings(settings_key,theme_key,day,night,is_active,active_visual_theme) values
('theme_classic','classic',
'{"wallpaper":"","icons":{"set":"rural","color":"#3f6f3a","size":"1.1em","strokeWidth":"1.8","opacity":"1"},"colors":{"primary":"#3f6f3a","secondary":"#6b4f2a","accent":"#c49a3a","text":"#302b20","heading":"#4d3820","muted":"#716955","background":"#f7f1df","surface":"#fffaf0","surfaceSoft":"#eee3c9","border":"#cdbf9f","focus":"#7b5b24","hover":"#e8edcf"},"states":{"success":"#3f6f3a","warning":"#b87952","error":"#a84d3f","info":"#5f8790"},"interaction":{"hoverOpacity":"1","activeOpacity":"1","disabledOpacity":".6"},"shape":{"radius":".4rem","buttonRadius":".35rem","borderWidth":"1px"},"shadow":{"card":"0 2px 8px rgb(77 56 32 / .10)","dropdown":"0 8px 24px rgb(77 56 32 / .14)","modal":"0 12px 36px rgb(77 56 32 / .18)","strength":"0 2px 8px rgb(77 56 32 / .10)"},"typography":{"headingFont":"Georgia, serif","bodyFont":"system-ui, sans-serif","headingSize":"1.35rem","bodySize":"1rem","headingWeight":"700","bodyWeight":"400","lineHeight":"1.55","letterSpacing":"normal"},"scrollbar":{"thumb":"#6b4f2a","track":"#eee3c9"},"effects":{"transparency":"0","blur":"0","waterDrop":"false","waterDropOpacity":"0","hover":"subtle","transition":"180ms ease"},"components":{"button":"solid","input":"solid","card":"flat","navigation":"solid"},"background":{"wallpaper":"","position":"center center","size":"cover","overlay":"none"},"spacing":{"density":"comfortable"}}'::jsonb,
'{"wallpaper":"","icons":{"set":"rural-night","color":"#d4c58f","size":"1.1em","strokeWidth":"1.75","opacity":".96"},"colors":{"primary":"#78a866","secondary":"#b9905e","accent":"#d4ae58","text":"#eee8d9","heading":"#e5c58f","muted":"#b9b8a7","background":"#182218","surface":"#202a20","surfaceSoft":"#293728","border":"#4e5b46","focus":"#e0bd6b","hover":"#344532"},"states":{"success":"#78a866","warning":"#d4ae58","error":"#d77b6f","info":"#79aeb5"},"interaction":{"hoverOpacity":"1","activeOpacity":"1","disabledOpacity":".6"},"shape":{"radius":".4rem","buttonRadius":".35rem","borderWidth":"1px"},"shadow":{"card":"0 2px 10px rgb(0 0 0 / .30)","dropdown":"0 8px 24px rgb(0 0 0 / .42)","modal":"0 12px 36px rgb(0 0 0 / .55)","strength":"0 2px 10px rgb(0 0 0 / .30)"},"typography":{"headingFont":"Georgia, serif","bodyFont":"system-ui, sans-serif","headingSize":"1.35rem","bodySize":"1rem","headingWeight":"700","bodyWeight":"400","lineHeight":"1.55","letterSpacing":"normal"},"scrollbar":{"thumb":"#b9905e","track":"#293728"},"effects":{"transparency":"0","blur":"0","waterDrop":"false","waterDropOpacity":"0","hover":"subtle","transition":"180ms ease"},"components":{"button":"solid","input":"solid","card":"flat","navigation":"solid"},"background":{"wallpaper":"","position":"center center","size":"cover","overlay":"none"},"spacing":{"density":"comfortable"}}'::jsonb,false,'classic')
on conflict(settings_key) do update set theme_key=excluded.theme_key,day=excluded.day,night=excluded.night,is_active=excluded.is_active,active_visual_theme=excluded.active_visual_theme,updated_at=now();

insert into public.theme_settings(settings_key,theme_key,day,night,is_active,active_visual_theme) values
('theme_glass','glass',
'{"wallpaper":"/assets/rural-bengal-wallpaper.svg","icons":{"set":"lucide","color":"#2f6f66","size":"1.1em","strokeWidth":"1.8","opacity":"1"},"colors":{"primary":"#2f6f66","secondary":"#496a78","accent":"#d3a84c","text":"#20333a","heading":"#254c52","muted":"#60747b","background":"#eaf6f7","surface":"rgb(255 255 255 / .58)","surfaceSoft":"rgb(255 255 255 / .38)","border":"rgb(255 255 255 / .55)","focus":"#2f8f87","hover":"rgb(255 255 255 / .72)"},"states":{"success":"#2f7d5b","warning":"#b98232","error":"#b44f4f","info":"#3f7f91"},"interaction":{"hoverOpacity":"1","activeOpacity":"1","disabledOpacity":".6"},"shape":{"radius":"1rem","buttonRadius":".8rem","borderWidth":"1px"},"shadow":{"card":"0 8px 28px rgb(31 73 82 / .14)","dropdown":"0 12px 32px rgb(31 73 82 / .18)","modal":"0 18px 48px rgb(31 73 82 / .22)","strength":"0 8px 28px rgb(31 73 82 / .14)"},"typography":{"headingFont":"Inter, system-ui, sans-serif","bodyFont":"Inter, system-ui, sans-serif","headingSize":"1.35rem","bodySize":"1rem","headingWeight":"750","bodyWeight":"400","lineHeight":"1.55","letterSpacing":"-0.01em"},"scrollbar":{"thumb":"#496a78","track":"rgb(255 255 255 / .38)"},"effects":{"transparency":".42","blur":"16px","waterDrop":"true","waterDropOpacity":".28","hover":"lift","transition":"220ms ease"},"components":{"button":"glass","input":"glass","card":"glass","navigation":"glass"},"background":{"wallpaper":"/assets/rural-bengal-wallpaper.svg","position":"center center","size":"cover","overlay":"rgba(234 246 247 / .22)"},"spacing":{"density":"comfortable"}}'::jsonb,
'{"wallpaper":"/assets/rural-bengal-night-wallpaper.svg","icons":{"set":"lucide","color":"#bfe1dc","size":"1.1em","strokeWidth":"1.8","opacity":".96"},"colors":{"primary":"#79c5b6","secondary":"#83a9bd","accent":"#e3bd67","text":"#e9f4f4","heading":"#bfe1dc","muted":"#a9c0c4","background":"#10252b","surface":"rgb(18 38 45 / .72)","surfaceSoft":"rgb(18 38 45 / .52)","border":"rgb(191 225 220 / .22)","focus":"#79c5b6","hover":"rgb(191 225 220 / .14)"},"states":{"success":"#79b98b","warning":"#e3bd67","error":"#d47d7d","info":"#7eb5c2"},"interaction":{"hoverOpacity":"1","activeOpacity":"1","disabledOpacity":".6"},"shape":{"radius":"1rem","buttonRadius":".8rem","borderWidth":"1px"},"shadow":{"card":"0 8px 30px rgb(0 0 0 / .34)","dropdown":"0 12px 34px rgb(0 0 0 / .42)","modal":"0 18px 52px rgb(0 0 0 / .52)","strength":"0 8px 30px rgb(0 0 0 / .34)"},"typography":{"headingFont":"Inter, system-ui, sans-serif","bodyFont":"Inter, system-ui, sans-serif","headingSize":"1.35rem","bodySize":"1rem","headingWeight":"750","bodyWeight":"400","lineHeight":"1.55","letterSpacing":"-0.01em"},"scrollbar":{"thumb":"#83a9bd","track":"rgb(18 38 45 / .52)"},"effects":{"transparency":".48","blur":"18px","waterDrop":"true","waterDropOpacity":".34","hover":"lift","transition":"220ms ease"},"components":{"button":"glass","input":"glass","card":"glass","navigation":"glass"},"background":{"wallpaper":"/assets/rural-bengal-night-wallpaper.svg","position":"center center","size":"cover","overlay":"rgba(16 37 43 / .34)"},"spacing":{"density":"comfortable"}}'::jsonb,true,'glass')
on conflict(settings_key) do update set theme_key=excluded.theme_key,day=excluded.day,night=excluded.night,is_active=excluded.is_active,active_visual_theme=excluded.active_visual_theme,updated_at=now();