import { useEffect,useState } from 'react'
import { useAuth } from '../../context'
import { hasPermission } from '../../services/permissionService'
import { listAccessData,saveRole,savePermission,saveRolePermissions } from '../../services/accessManagementService'
import { createAuditLog } from '../../services/auditService'
import { AdminLayout } from '../../components/admin'
import { Button,Input,Textarea,Checkbox,Select,Loading,ErrorState } from '../../components/ui'
const R={role_key:'',role_name:'',description:'',is_active:true};const P={permission_key:'',permission_name:'',description:'',is_active:true}
export default function AccessManagement(){const{user,status}=useAuth();const[allowed,setAllowed]=useState(false),[ready,setReady]=useState(false),[roles,setRoles]=useState([]),[permissions,setPermissions]=useState([]),[links,setLinks]=useState([]),[role,setRole]=useState(R),[permission,setPermission]=useState(P),[selectedRole,setSelectedRole]=useState(''),[selectedIds,setSelectedIds]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(null)
 async function load(){const p=await hasPermission('user_manage');setAllowed(p);if(!p){setReady(true);return}const d=await listAccessData();setRoles(d.roles);setPermissions(d.permissions);setLinks(d.rolePermissions);if(!selectedRole&&d.roles[0]){setSelectedRole(d.roles[0].role_id);setSelectedIds(d.rolePermissions.filter(x=>x.role_id===d.roles[0].role_id).map(x=>x.permission_id))}setReady(true)}
 useEffect(()=>{if(status==='loading')return;if(!user){window.location.href=(import.meta.env.BASE_URL||'/')+'login';return}load().catch(e=>{setError(e);setReady(true)})},[status,user])
 function changeRole(k,v){setRole(x=>({...x,[k]:v}));setError(null)};function changePermission(k,v){setPermission(x=>({...x,[k]:v}));setError(null)}
 async function submitRole(e){e.preventDefault();setBusy(true);try{const saved=await saveRole(role.role_id,role);await createAuditLog({actionKey:role.role_id?'update':'create',module:'roles',recordId:saved.role_id,details:{fields:['role_key','role_name','description','is_active']}});setRole(R);await load()}catch(e2){setError(e2)}finally{setBusy(false)}}
 async function submitPermission(e){e.preventDefault();setBusy(true);try{const saved=await savePermission(permission.permission_id,permission);await createAuditLog({actionKey:permission.permission_id?'update':'create',module:'permissions',recordId:saved.permission_id,details:{fields:['permission_key','permission_name','description','is_active']}});setPermission(P);await load()}catch(e2){setError(e2)}finally{setBusy(false)}}
 function chooseRole(id){setSelectedRole(id);setSelectedIds(links.filter(x=>x.role_id===id).map(x=>x.permission_id));const found=roles.find(x=>x.role_id===id);if(found)setRole({...found})}
 async function saveLinks(){setBusy(true);try{await saveRolePermissions(selectedRole,selectedIds);await createAuditLog({actionKey:'update',module:'role_permissions',recordId:selectedRole,details:{permission_ids:selectedIds}});await load()}catch(e2){setError(e2)}finally{setBusy(false)}}
 if(status==='loading'||!ready)return <Loading/>;if(!allowed)return <ErrorState description="আপনার roles/permissions পরিচালনার অনুমতি নেই।"/>
 return <AdminLayout user={user} title="Roles & Permissions"><div className="admin-page-grid"><section className="admin-form"><h3>Role</h3><form onSubmit={submitRole}><Input id="role-key" label="role_key" value={role.role_key||''} onChange={e=>changeRole('role_key',e.target.value)} disabled={busy}/><Input id="role-name" label="role_name" value={role.role_name||''} onChange={e=>changeRole('role_name',e.target.value)} disabled={busy}/><Textarea id="role-description" label="description" value={role.description||''} onChange={e=>changeRole('description',e.target.value)} disabled={busy}/><Checkbox id="role-active" label="is_active" checked={role.is_active!==false} onChange={e=>changeRole('is_active',e.target.checked)} disabled={busy}/><Button type="submit" disabled={busy}>Role সংরক্ষণ</Button></form><hr/><h3>Permission</h3><form onSubmit={submitPermission}><Input id="permission-key" label="permission_key" value={permission.permission_key||''} onChange={e=>changePermission('permission_key',e.target.value)} disabled={busy}/><Input id="permission-name" label="permission_name" value={permission.permission_name||''} onChange={e=>changePermission('permission_name',e.target.value)} disabled={busy}/><Textarea id="permission-description" label="description" value={permission.description||''} onChange={e=>changePermission('description',e.target.value)} disabled={busy}/><Checkbox id="permission-active" label="is_active" checked={permission.is_active!==false} onChange={e=>changePermission('is_active',e.target.checked)} disabled={busy}/><Button type="submit" disabled={busy}>Permission সংরক্ষণ</Button></form></section><section className="admin-form"><h3>Role Permissions</h3><Select id="access-role" label="Role" value={selectedRole} onChange={e=>chooseRole(e.target.value)} options={roles.map(x=>({value:x.role_id,label:x.role_name}))} disabled={busy}/>{permissions.map(p=><Checkbox key={p.permission_id} id={'perm-'+p.permission_id} label={`${p.permission_name} (${p.permission_key})`} checked={selectedIds.includes(p.permission_id)} onChange={()=>setSelectedIds(ids=>ids.includes(p.permission_id)?ids.filter(id=>id!==p.permission_id):[...ids,p.permission_id])} disabled={busy||p.is_active===false}/>)}<Button type="button" onClick={saveLinks} disabled={busy||!selectedRole}>Permissions সংরক্ষণ</Button></section></div>{error?<ErrorState description={error.message}/>:null}</AdminLayout>}
