import { useCallback, useEffect, useState } from 'react'
import { useAuth } from '../../context'
import { hasPermission } from '../../services/permissionService'
import { getDatabaseStorageInfo } from '../../services/databaseStorageService'
import { getHomepageSettings, saveHomepageSettings } from '../../services/homepageService'
import { AdminLayout } from '../../components/admin'
import { Button, Input, Loading, ErrorState, EmptyState } from '../../components/ui'

function formatBytes(value) { const n=Number(value||0); if(!n)return '0 B'; const units=['B','KB','MB','GB','TB']; let i=0,size=n; while(size>=1024&&i<units.length-1){size/=1024;i+=1} return size.toFixed(size>=10||i===0?0:1)+' '+units[i] }
function Stat({ label, value }) { return <article className="admin-stat-card"><span>{label}</span><strong>{value}</strong></article> }

export default function DatabaseStorageInformation() {
 const {user,status}=useAuth(); const [allowed,setAllowed]=useState(false),[ready,setReady]=useState(false),[info,setInfo]=useState(null),[error,setError]=useState(null),[busy,setBusy]=useState(false),[settings,setSettings]=useState(null),[settingsSaving,setSettingsSaving]=useState(false)
 const load=useCallback(async()=>{setBusy(true);setError(null);try{const [permission,data,homepage]=await Promise.all([hasPermission('settings_manage'),getDatabaseStorageInfo(),getHomepageSettings()]);setAllowed(permission);if(permission){setInfo(data);setSettings(homepage)}setReady(true)}catch(e){setError(e);setReady(true)}finally{setBusy(false)}},[])
 useEffect(()=>{if(status==='loading')return;if(!user){window.location.href=(import.meta.env.BASE_URL||'/')+'login';return}load()},[status,user,load])
 async function saveAutoScroll(){setSettingsSaving(true);setError(null);try{const saved=await saveHomepageSettings({...settings,horizontalAutoScroll:{...settings.horizontalAutoScroll,intervalMs:Math.max(1000,Math.min(60000,Number(settings.horizontalAutoScroll?.intervalMs)||4000))}});setSettings(saved)}catch(e){setError(e)}finally{setSettingsSaving(false)}}
 if(status==='loading'||!ready)return <Loading/>; if(error&&!allowed)return <ErrorState description={error.message||'ডাটাবেজ ও স্টোরেজ তথ্য লোড করা যায়নি।'}/>; if(!allowed)return <ErrorState description="আপনার এই তথ্য দেখার অনুমতি নেই।"/>; if(!info)return <ErrorState description={error?.message||'তথ্য পাওয়া যায়নি।'}/>
 const d=info.database,s=info.storage,auto=settings?.horizontalAutoScroll||{}
 return <AdminLayout user={user} title="Database & Storage Information"><section className="admin-form"><div className="admin-section-heading"><div><h3>Supabase Database ও Storage</h3><p>তথ্য সরাসরি বর্তমান Production Supabase project থেকে পড়া হচ্ছে।</p></div><Button type="button" variant="secondary" onClick={load} disabled={busy}>{busy?'রিফ্রেশ হচ্ছে…':'রিফ্রেশ'}</Button></div><p><strong>Project:</strong> yopfogoyjxwxplnabqii · <strong>Bucket:</strong> {s.bucket} · <strong>সর্বশেষ:</strong> {new Date(info.refreshedAt).toLocaleString('bn-BD')}</p></section>
 <section className="admin-form"><h3>Horizontal Auto-scroll</h3><p className="admin-intro">সাইটের সব horizontal scroll অংশ নির্দিষ্ট interval অনুযায়ী এক ধাপ করে চলবে। ইউজার touch/drag/wheel করলে ১ মিনিট pause থাকবে।</p><Input id="horizontal-auto-scroll-interval" type="number" min="1" max="60" step="1" label="Auto-scroll interval (সেকেন্ড)" value={Math.round(Number(auto.intervalMs||4000)/1000)} onChange={e=>setSettings(c=>({...c,horizontalAutoScroll:{...(c?.horizontalAutoScroll||{}),enabled:true,intervalMs:Math.max(1000,Math.min(60000,(Number(e.target.value)||4)*1000))}}))}/><Button type="button" onClick={saveAutoScroll} disabled={settingsSaving}>{settingsSaving?'সংরক্ষণ হচ্ছে…':'Auto-scroll সেটিংস সংরক্ষণ করুন'}</Button></section>
 <section><h3>Database</h3><div className="admin-stat-grid"><Stat label="মিডিয়া রেকর্ড" value={d.media}/><Stat label="Storage media" value={d.uploadedMedia}/><Stat label="External media" value={d.externalMedia}/><Stat label="অ্যালবাম" value={d.albums}/><Stat label="পেজ" value={d.pages}/><Stat label="পোস্ট" value={d.posts}/><Stat label="Media file size" value={formatBytes(d.mediaBytes)}/></div></section>
 <section><h3>Storage Bucket: {s.bucket}</h3><div className="admin-stat-grid"><Stat label="Storage objects" value={s.objects}/><Stat label="Storage size" value={formatBytes(s.bytes)}/></div>{!s.objects?<EmptyState description="বর্তমানে এই bucket-এ কোনো object পাওয়া যায়নি।"/>:<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>নাম</th><th>ধরন</th><th>আকার</th><th>আপডেট</th></tr></thead><tbody>{s.objectsList.map(item=><tr key={item.id||item.name}><td>{item.name}</td><td>{item.metadata?.mimetype||'—'}</td><td>{formatBytes(item.metadata?.size)}</td><td>{item.updated_at?new Date(item.updated_at).toLocaleString('bn-BD'):'—'}</td></tr>)}</tbody></table></div>}</section></AdminLayout>
}
