import { useEffect, useState } from 'react'
import { useAuth } from '../../context'
import { hasPermission } from '../../services/permissionService'
import { getHomepageSettings, saveHomepageSettings } from '../../services/homepageService'
import { listPublishedPages } from '../../services/pageService'
import { createAuditLog } from '../../services/auditService'
import { AdminLayout } from '../../components/admin'
import { Button, Input, Checkbox, Textarea, Loading, ErrorState, DragReorderList } from '../../components/ui'
function togglePage(list,pageId){const exists=list.some(x=>x.page_id===pageId);return exists?list.filter(x=>x.page_id!==pageId):[...list,{page_id:pageId,enabled:true}]}
export default function HomepageManagement(){const{user,status}=useAuth();const[allowed,setAllowed]=useState(false),[ready,setReady]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(null),[config,setConfig]=useState(null),[pages,setPages]=useState([]),[json,setJson]=useState('')
 useEffect(()=>{if(status==='loading')return;if(!user){window.location.href=(import.meta.env.BASE_URL||'/')+'login';return}Promise.all([hasPermission('homepage_manage'),getHomepageSettings(),listPublishedPages()]).then(([p,s,pg])=>{setAllowed(p);setConfig(s);setJson(JSON.stringify(s,null,2));setPages(pg);setReady(true)}).catch(e=>{setError(e);setReady(true)})},[status,user])
 const update=(section,key,value)=>setConfig(c=>({...c,[section]:{...c[section],[key]:value}}))
 function selectTabPage(id){setConfig(c=>({...c,topicTabs:{...c.topicTabs,items:togglePage(c.topicTabs.items||[],id)}}))};function selectCardPage(id){setConfig(c=>({...c,pageCards:{...c.pageCards,items:togglePage(c.pageCards.items||[],id)}}))}
 function changeAdvanced(value){setJson(value);try{setConfig(JSON.parse(value));setError(null)}catch(e){setError(new Error('Advanced config JSON সঠিক নয়।'))}}
 async function handleSave(e){e.preventDefault();setSaving(true);setError(null);try{const saved=await saveHomepageSettings(config);setConfig(saved);setJson(JSON.stringify(saved,null,2));await createAuditLog({actionKey:'update',module:'homepage',details:{settings:saved}})}catch(e2){setError(e2)}finally{setSaving(false)}}
 const tabs=config?.topicTabs?.items||[],cards=config?.pageCards?.items||[];if(status==='loading'||!ready)return <Loading/>;if(!allowed)return <ErrorState description="আপনার হোমপেজ ম্যানেজমেন্টের অনুমতি নেই।"/>
 return <AdminLayout user={user} title="হোমপেজ ম্যানেজমেন্ট"><form className="admin-management" onSubmit={handleSave}><section className="admin-form"><h3>Hero</h3><Checkbox id="hero-enabled" label="Hero দেখান" checked={config.hero.enabled!==false} onChange={e=>update('hero','enabled',e.target.checked)}/><Input id="hero-title" label="Hero শিরোনাম" value={config.hero.title||''} onChange={e=>update('hero','title',e.target.value)}/><Input id="hero-subtitle" label="Hero উপশিরোনাম" value={config.hero.subtitle||''} onChange={e=>update('hero','subtitle',e.target.value)}/><Checkbox id="hero-slogan" label="Slogan দেখান" checked={config.hero.showSlogan!==false} onChange={e=>update('hero','showSlogan',e.target.checked)}/></section>
 <section className="admin-form"><h3>পেজ → ট্যাব</h3><Checkbox id="tabs-enabled" label="ট্যাব দেখান" checked={config.topicTabs.enabled!==false} onChange={e=>update('topicTabs','enabled',e.target.checked)}/><div className="admin-list">{pages.map(page=>{const selected=tabs.some(x=>x.page_id===page.page_id);return <div className="admin-list__item" key={page.page_id}><Checkbox id={'tab-'+page.page_id} label={page.page_title} checked={selected} onChange={()=>selectTabPage(page.page_id)}/></div>})}</div><DragReorderList items={tabs} getKey={(item)=>item.page_id} onReorder={(items)=>setConfig(c=>({...c,topicTabs:{...c.topicTabs,items}}))} renderItem={(item)=><span>{pages.find(page=>page.page_id===item.page_id)?.page_title || item.page_id}</span>} label="হোমপেজ ট্যাবের ক্রম" /></section>
 <section className="admin-form"><h3>পেজ → কার্ড</h3><Checkbox id="cards-enabled" label="কার্ড দেখান" checked={config.pageCards?.enabled!==false} onChange={e=>update('pageCards','enabled',e.target.checked)}/><Input id="cards-title" label="কার্ড সেকশনের শিরোনাম" value={config.pageCards?.title||''} onChange={e=>update('pageCards','title',e.target.value)}/><Input id="cards-limit" type="number" min="1" max="50" label="কার্ড সংখ্যা" value={config.pageCards?.limit||8} onChange={e=>update('pageCards','limit',Number(e.target.value)||8)}/><div className="admin-list">{pages.map(page=>{const selected=cards.some(x=>x.page_id===page.page_id);return <div className="admin-list__item" key={page.page_id}><Checkbox id={'card-'+page.page_id} label={page.page_title} checked={selected} onChange={()=>selectCardPage(page.page_id)}/></div>})}</div><DragReorderList items={cards} getKey={(item)=>item.page_id} onReorder={(items)=>setConfig(c=>({...c,pageCards:{...c.pageCards,items}}))} renderItem={(item)=><span>{pages.find(page=>page.page_id===item.page_id)?.page_title || item.page_id}</span>} label="হোমপেজ কার্ডের ক্রম" /></section>
 <section className="admin-form"><h3>হোমপেজ সেকশন</h3><Checkbox id="info-enabled" label="গ্রামের তথ্য" checked={config.information.enabled!==false} onChange={e=>update('information','enabled',e.target.checked)}/><Checkbox id="posts-enabled" label="পোস্ট" checked={config.posts.enabled!==false} onChange={e=>update('posts','enabled',e.target.checked)}/><Input id="posts-title" label="পোস্ট শিরোনাম" value={config.posts.title||''} onChange={e=>update('posts','title',e.target.value)}/><Input id="posts-limit" type="number" min="1" max="30" label="পোস্ট সংখ্যা" value={config.posts.limit||6} onChange={e=>update('posts','limit',Number(e.target.value)||6)}/><Checkbox id="gallery-enabled" label="ছবি ও ভিডিও Gallery" checked={config.mediaGallery.enabled!==false} onChange={e=>update('mediaGallery','enabled',e.target.checked)}/><Input id="gallery-title" label="Gallery শিরোনাম" value={config.mediaGallery.title||''} onChange={e=>update('mediaGallery','title',e.target.value)}/><Input id="gallery-subtitle" label="Gallery উপশিরোনাম" value={config.mediaGallery.subtitle||''} onChange={e=>update('mediaGallery','subtitle',e.target.value)}/><Checkbox id="gallery-show-all" label="Gallery-তে সব দেখান" checked={config.mediaGallery.showAll!==false} onChange={e=>update('mediaGallery','showAll',e.target.checked)}/><Textarea id="gallery-album-ids" label="Gallery albumIds (JSON array)" value={JSON.stringify(config.mediaGallery.albumIds||[])} onChange={e=>{try{update('mediaGallery','albumIds',JSON.parse(e.target.value||'[]'));setError(null)}catch{setError(new Error('albumIds JSON সঠিক নয়।'))}}}/><Checkbox id="albums-enabled" label="অ্যালবাম" checked={config.albums.enabled!==false} onChange={e=>update('albums','enabled',e.target.checked)}/><Input id="albums-title" label="অ্যালবাম শিরোনাম" value={config.albums.title||''} onChange={e=>update('albums','title',e.target.value)}/><Input id="albums-limit" type="number" min="1" max="20" label="অ্যালবাম সংখ্যা" value={config.albums.limit||4} onChange={e=>update('albums','limit',Number(e.target.value)||4)}/></section>
 <section className="admin-form"><h3>Advanced config — 100% DB JSON</h3><p className="admin-intro">config-এর কোনো অতিরিক্ত key বাদ না দিয়ে সম্পূর্ণ JSON সম্পাদনা করা যাবে।</p><Textarea id="homepage-config-json" label="config" value={json} onChange={e=>changeAdvanced(e.target.value)} /></section>
 <div className="admin-form__actions"><Button type="submit" disabled={saving}>{saving?'সংরক্ষণ হচ্ছে…':'হোমপেজ সেটিংস সংরক্ষণ করুন'}</Button></div>{error?<ErrorState description={error.message}/>:null}</form></AdminLayout>}
