import { useEffect,useState } from 'react'
import { useAuth } from '../../context'
import { hasPermission } from '../../services/permissionService'
import { getSidebarSettings,saveSidebarSettings } from '../../services/sidebarService'
import { listPublishedPages } from '../../services/pageService'
import { createAuditLog } from '../../services/auditService'
import { AdminLayout } from '../../components/admin'
import { Button,Checkbox,Textarea,Loading,ErrorState,DragReorderList } from '../../components/ui'
function togglePage(list,pageId){const exists=list.some(x=>x.page_id===pageId);return exists?list.filter(x=>x.page_id!==pageId):[...list,{page_id:pageId,enabled:true}]}
export default function SidebarManagement(){const{user,status}=useAuth();const[allowed,setAllowed]=useState(false),[ready,setReady]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(null),[config,setConfig]=useState(null),[pages,setPages]=useState([]),[json,setJson]=useState('')
 useEffect(()=>{if(status==='loading')return;if(!user){window.location.href=(import.meta.env.BASE_URL||'/')+'login';return}Promise.all([hasPermission('sidebar_manage'),getSidebarSettings(),listPublishedPages()]).then(([p,s,pg])=>{setAllowed(p);setConfig(s);setJson(JSON.stringify(s,null,2));setPages(pg);setReady(true)}).catch(e=>{setError(e);setReady(true)})},[status,user])
 function selectPage(id){setConfig(c=>({...c,items:togglePage(c.items||[],id)}))}
 function changeAdvanced(value){setJson(value);try{setConfig(JSON.parse(value));setError(null)}catch{setError(new Error('Sidebar config JSON সঠিক নয়।'))}}
 async function handleSave(e){e.preventDefault();setSaving(true);setError(null);try{const saved=await saveSidebarSettings(config);setConfig(saved);setJson(JSON.stringify(saved,null,2));await createAuditLog({actionKey:'update',module:'sidebar',details:{settings:saved}})}catch(e2){setError(e2)}finally{setSaving(false)}}
 const selected=config?.items||[];if(status==='loading'||!ready)return <Loading/>;if(!allowed)return <ErrorState description="আপনার সাইডবার ম্যানেজমেন্টের অনুমতি নেই।"/>
 return <AdminLayout user={user} title="সাইডবার ম্যানেজমেন্ট"><form className="admin-management" onSubmit={handleSave}><section className="admin-form"><Checkbox id="sidebar-enabled" label="সাইডবার চালু রাখুন" checked={config.enabled!==false} onChange={e=>setConfig(c=>({...c,enabled:e.target.checked}))}/><p className="admin-intro">প্রকাশিত পেজ নির্বাচন করুন এবং ক্রম সাজান।</p><div className="admin-list">{pages.map(page=>{const on=selected.some(x=>x.page_id===page.page_id);return <div className="admin-list__item" key={page.page_id}><Checkbox id={'sidebar-page-'+page.page_id} label={page.page_title} checked={on} onChange={()=>selectPage(page.page_id)}/></div>})}</div><DragReorderList items={selected} getKey={(item)=>item.page_id} onReorder={(items)=>setConfig(c=>({...c,items}))} renderItem={(item)=><span>{pages.find(page=>page.page_id===item.page_id)?.page_title || item.page_id}</span>} label="সাইডবার পেজের ক্রম" /></section><section className="admin-form"><h3>Advanced config — 100% DB JSON</h3><p className="admin-intro">config-এর items, enabled, cards এবং ভবিষ্যতের অতিরিক্ত key-সহ সম্পূর্ণ JSON editable।</p><Textarea id="sidebar-config-json" label="config" value={json} onChange={e=>changeAdvanced(e.target.value)}/></section><div className="admin-form__actions"><Button type="submit" disabled={saving}>{saving?'সংরক্ষণ হচ্ছে…':'সাইডবার সেটিংস সংরক্ষণ করুন'}</Button></div>{error?<ErrorState description={error.message}/>:null}</form></AdminLayout>}
