import { useEffect, useState } from 'react'
import { useAuth } from '../../context'
import { hasPermission } from '../../services/permissionService'
import { assignUserRole, inviteUser, listManagedUsers, listRoles } from '../../services/userService'
import { getProfileForManagement, updateProfileForManagement } from '../../services/profileManagementService'
import { createAuditLog } from '../../services/auditService'
import { AdminLayout } from '../../components/admin'
import { Button, Input, Select, Textarea, Checkbox, Loading, ErrorState, EmptyState } from '../../components/ui'

const EMPTY={profile_id:'',email:'',phone:'',display_name:'',bio:'',link:'',profile_image_url:'',is_active:true,is_protected:false}
export default function UsersManagement(){
 const {user,status}=useAuth(); const [allowed,setAllowed]=useState(false),[ready,setReady]=useState(false),[users,setUsers]=useState([]),[roles,setRoles]=useState([]),[selected,setSelected]=useState(null),[values,setValues]=useState(EMPTY),[busy,setBusy]=useState(false),[error,setError]=useState(null),[inviteEmail,setInviteEmail]=useState(''),[inviteName,setInviteName]=useState(''),[inviteMessage,setInviteMessage]=useState('')
 async function load(){const permission=await hasPermission('user_manage');setAllowed(permission);if(!permission){setReady(true);return}const [userData,roleData]=await Promise.all([listManagedUsers(),listRoles()]);setUsers(userData);setRoles(roleData);setReady(true)}
 useEffect(()=>{if(status==='loading')return;if(!user){window.location.href=(import.meta.env.BASE_URL||'/')+'login';return}load().catch(e=>{setError(e);setReady(true)})},[status,user])
 async function editProfile(item){setBusy(true);setError(null);try{const profile=await getProfileForManagement(item.profile_id);setSelected(item.profile_id);setValues({...EMPTY,...profile})}catch(e){setError(e)}finally{setBusy(false)}}
 function change(k,v){setValues(x=>({...x,[k]:v}));setError(null)}
 async function saveProfile(e){e.preventDefault();setBusy(true);setError(null);try{const saved=await updateProfileForManagement(selected,values);await createAuditLog({actionKey:'update',module:'profiles',recordId:saved.profile_id,details:{fields:['email','phone','display_name','bio','link','profile_image_url','is_active','is_protected']}});setValues({...EMPTY,...saved});await load()}catch(e){setError(e)}finally{setBusy(false)}}
 async function changeRole(profileId,roleId){setBusy(true);setError(null);try{await assignUserRole(profileId,roleId);await createAuditLog({actionKey:'role_change',module:'user_roles',recordId:profileId,details:{role_id:roleId}});await load()}catch(e){setError(e)}finally{setBusy(false)}}
 async function handleInvite(event){event.preventDefault();setBusy(true);setError(null);setInviteMessage('');try{const invited=await inviteUser(inviteEmail.trim(),inviteName.trim());await createAuditLog({actionKey:'invite',module:'users',recordId:invited?.id||null,details:{email:inviteEmail.trim()}});setInviteEmail('');setInviteName('');setInviteMessage('আমন্ত্রণ ইমেইল পাঠানো হয়েছে।');await load()}catch(e){setError(e)}finally{setBusy(false)}}
 if(status==='loading'||!ready)return <Loading/>;if(error&&!allowed)return <ErrorState description={error.message||'ইউজার ম্যানেজমেন্ট লোড করা যায়নি।'}/>;if(!allowed)return <ErrorState description="আপনার ইউজার পরিচালনার অনুমতি নেই।"/>
 return <AdminLayout user={user} title="Users & Roles"><p className="admin-intro">profiles-এর সব editable field, role এবং user invitation এখান থেকে পরিচালনা করুন।</p>
 <section className="admin-form user-invite-form"><h3>নতুন ব্যবহারকারী আমন্ত্রণ</h3><form onSubmit={handleInvite}><Input id="invite-email" name="invite_email" type="email" label="ইমেইল" value={inviteEmail} onChange={e=>setInviteEmail(e.target.value)} disabled={busy} required/><Input id="invite-name" name="invite_name" label="নাম (ঐচ্ছিক)" value={inviteName} onChange={e=>setInviteName(e.target.value)} disabled={busy}/><Button type="submit" disabled={busy}>{busy?'পাঠানো হচ্ছে…':'আমন্ত্রণ পাঠান'}</Button></form>{inviteMessage?<p className="admin-success">{inviteMessage}</p>:null}</section>
 {selected?<section className="admin-form"><h3>Profile সম্পাদনা</h3><form onSubmit={saveProfile}><Input id="profile-email" label="email" type="email" value={values.email} onChange={e=>change('email',e.target.value)} disabled={busy}/><Input id="profile-phone" label="phone" value={values.phone} onChange={e=>change('phone',e.target.value)} disabled={busy}/><Input id="profile-name" label="display_name" value={values.display_name} onChange={e=>change('display_name',e.target.value)} disabled={busy}/><Textarea id="profile-bio" label="bio" value={values.bio} onChange={e=>change('bio',e.target.value)} disabled={busy}/><Input id="profile-link" label="link" type="url" value={values.link} onChange={e=>change('link',e.target.value)} disabled={busy}/><Input id="profile-image" label="profile_image_url" type="url" value={values.profile_image_url} onChange={e=>change('profile_image_url',e.target.value)} disabled={busy}/><Checkbox id="profile-active" label="is_active" checked={values.is_active!==false} onChange={e=>change('is_active',e.target.checked)} disabled={busy}/><Checkbox id="profile-protected" label="is_protected" checked={values.is_protected===true} onChange={e=>change('is_protected',e.target.checked)} disabled={busy}/><div className="admin-form__actions"><Button type="submit" disabled={busy}>{busy?'সংরক্ষণ হচ্ছে…':'Profile সংরক্ষণ'}</Button><Button type="button" variant="secondary" onClick={()=>setSelected(null)} disabled={busy}>বন্ধ</Button></div></form></section>:null}
 {!users.length?<EmptyState description="এখনও কোনো নিবন্ধিত ব্যবহারকারী নেই।"/>:<div className="admin-list">{users.map(item=>{const current=item.user_roles?.[0]?.role_id||'';const protectedAdmin=item.is_protected===true;return <article className="admin-list__item" key={item.profile_id}><div><h4>{item.display_name||item.email||'ব্যবহারকারী'}</h4><p>{item.email||''}</p>{protectedAdmin?<p className="admin-list__status">🔒 Protected Admin</p>:null}</div><div className="admin-list__actions"><Button type="button" variant="secondary" onClick={()=>editProfile(item)} disabled={busy}>Profile</Button><Select id={'role-'+item.profile_id} aria-label="ভূমিকা" value={current} onChange={e=>changeRole(item.profile_id,e.target.value)} options={roles.map(r=>({value:r.role_id,label:r.role_name}))} disabled={busy||protectedAdmin}/></div></article>})}</div>}{error?<ErrorState description={error.message||'ব্যবহারকারী পরিবর্তন করা যায়নি.'}/>:null}</AdminLayout>
}
